"""Shiny-Compatible PDF Report Generation Module for QWIM Analytics.

This module provides PDF report generation capabilities specifically designed
to be called from Shiny dashboard buttons following QWIM project coding standards.

Report generation uses the Typst typesetting system to compile professional
PDF documents from the ``report_QWIM.typ`` template.  Data is passed to
Typst via JSON files that the template reads with ``json()`` calls, and
charts are included as SVG images generated by ``plotnine``.

Pipeline
--------
1.  Export dashboard data → JSON files (``report_data_export``).
    Client information (``client_info.json``) is sourced directly from
    ``reactives_shiny["Data_Clients"]`` via
    ``utils_reporting.build_client_info_json_from_reactives()``.
    Subtab inputs/outputs (``inputs_json/*.json`` and
    ``outputs_json/*.json``) are sourced from
    ``reactives_shiny["Data_Results"]`` via
    ``utils_reporting.build_results_data_json_from_reactives()``.
    When a ``Data_Results`` key is not yet populated (``None``), each
    export function falls back to the legacy ``User_Inputs_Shiny`` /
    ``Inner_Variables_Shiny`` keys so that report generation always
    produces valid JSON.
2.  Export dashboard charts → SVG images (``report_plot_export``)
3.  Copy ``.typ`` template + JSON + SVG into a temp directory
4.  Compile ``report_QWIM.typ`` → PDF via ``typst`` Python bindings or CLI

Dependencies
-----------
* typst: Typst compilation system (CLI or Python bindings)
* polars: For high-performance DataFrames
* numpy: For numerical utilities
* plotnine: For static SVG chart generation

Shiny Integration
----------------
This module is designed to be called from Shiny server functions in the
"Reporting" subtab with proper error handling and status reporting.

Example Usage from Shiny
------------------------
    from src.dashboard.reporting.report_QWIM import generate_report_PDF

    Success_Flag, Output_Message, File_Path = generate_report_PDF(
        report_title="QWIM Portfolio Analysis",
        output_filename="qwim_report_20260301.pdf",
        reactives_shiny=Reactives_Shiny_Dict,
        user_id="user_001",
    )
"""

from __future__ import annotations

import datetime
import logging
import shutil
import subprocess
import tempfile

from pathlib import Path
from typing import Any

import numpy as np
import polars as pl

from src.dashboard.reporting.report_data_export import export_all_report_data
from src.dashboard.reporting.report_plot_export import export_all_report_plots


logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_REPORTING_DIR = Path(__file__).resolve().parent


# =========================================================================
# Utility helpers (kept for backward compatibility and tests)
# =========================================================================


def safe_is_finite_value(value: Any) -> bool:
    """Safely check if a value is finite.

    Parameters
    ----------
    value : Any
        Value to check for finiteness.

    Returns
    -------
    bool
        ``True`` if *value* is finite, ``False`` otherwise.
    """
    if value is None:
        return False
    if not isinstance(value, (int, float, np.number)):
        return False
    try:
        return bool(np.isfinite(value))
    except Exception:
        return False


def safe_polars_column_access(
    polars_DF: pl.DataFrame | None,
    column_name: str,
    operation: str = "sum",
    default_value: Any = 0,
) -> Any:
    """Safely access polars DataFrame columns with error handling.

    Parameters
    ----------
    polars_DF : pl.DataFrame | None
        Source polars DataFrame.
    column_name : str
        Name of column to access.
    operation : str
        Operation to perform (``"sum"``, ``"mean"``, ``"n_unique"``,
        ``"first"``, ``"count"``).
    default_value : Any
        Default value if operation fails.

    Returns
    -------
    Any
        Result of operation or *default_value*.
    """
    if polars_DF is None:
        logger.warning("DataFrame is None for column %s", column_name)
        return default_value
    if polars_DF.height == 0 or polars_DF.width == 0:
        logger.warning("DataFrame is empty for column %s", column_name)
        return default_value
    if column_name not in polars_DF.columns:
        logger.warning("Column '%s' not found. Available: %s", column_name, polars_DF.columns)
        return default_value

    try:
        numeric_types = (
            pl.Int64,
            pl.Int32,
            pl.Float64,
            pl.Float32,
            pl.Int8,
            pl.Int16,
            pl.UInt32,
            pl.UInt64,
        )
        col_dtype = polars_DF.schema[column_name]
        op_map: dict[str, str] = {
            "sum": "sum",
            "mean": "mean",
            "n_unique": "n_unique",
            "first": "first",
            "count": "count",
        }

        if operation in ("sum", "mean") and col_dtype not in numeric_types:
            logger.warning("Column '%s' is not numeric for %s", column_name, operation)
            return default_value

        if operation not in op_map:
            logger.warning("Unknown operation '%s' for column %s", operation, column_name)
            return default_value

        expr = getattr(pl.col(column_name), op_map[operation])()
        result = polars_DF.select(expr).item()
        return result if result is not None else default_value
    except Exception as column_error:
        logger.warning("Error accessing column '%s': %s", column_name, column_error)
        return default_value


def validate_polars_DF(
    polars_DF: pl.DataFrame | None,
    dataframe_name: str = "DataFrame",
) -> bool:
    """Validate polars DataFrame structure and content.

    Parameters
    ----------
    polars_DF : pl.DataFrame | None
        DataFrame to validate.
    dataframe_name : str
        Name of DataFrame for logging.

    Returns
    -------
    bool
        ``True`` if DataFrame is valid and usable.
    """
    if polars_DF is None:
        logger.warning("%s is None", dataframe_name)
        return False
    if not isinstance(polars_DF, pl.DataFrame):
        logger.warning("%s is not a polars DataFrame: %s", dataframe_name, type(polars_DF))
        return False
    if polars_DF.height == 0 or polars_DF.width == 0:
        logger.warning("%s is empty", dataframe_name)
        return False
    logger.info("%s is valid: %d rows, %d cols", dataframe_name, polars_DF.height, polars_DF.width)
    return True


# =========================================================================
# Sample data factories (kept for backward compat and tests)
# =========================================================================


def create_sample_personal_info_dataframe() -> pl.DataFrame:
    """Create sample personal-info DataFrame for testing.

    Returns
    -------
    pl.DataFrame
        Sample personal information DataFrame.
    """
    return pl.DataFrame(
        {
            "Investor_ID": ["INV001", "INV002", "INV003"],
            "Investor_Type": ["Primary", "Spouse", "Dependent"],
            "Name_First": ["John", "Jane", "Junior"],
            "Name_Last": ["Smith", "Smith", "Smith"],
            "Age_Current": [65, 62, 30],
            "Age_Retirement": [67, 65, 65],
            "State_Residence": ["California", "California", "New York"],
            "Risk_Tolerance": ["Moderate", "Conservative", "Aggressive"],
        },
    )


def create_sample_assets_dataframe() -> pl.DataFrame:
    """Create sample assets DataFrame for testing.

    Returns
    -------
    pl.DataFrame
        Sample assets DataFrame.
    """
    return pl.DataFrame(
        {
            "Investor_ID": ["INV001", "INV001", "INV002", "INV002", "INV003"],
            "Investor_Type": ["Primary", "Primary", "Spouse", "Spouse", "Dependent"],
            "Asset_Category": ["401k", "IRA", "Roth IRA", "Savings", "Brokerage"],
            "Asset_Value": [450000, 125000, 85000, 25000, 15000],
            "Asset_Type": [
                "Tax Deferred",
                "Tax Deferred",
                "Tax Free",
                "Taxable",
                "Taxable",
            ],
            "Institution_Name": [
                "Fidelity",
                "Vanguard",
                "Charles Schwab",
                "Bank of America",
                "E*TRADE",
            ],
        },
    )


def create_sample_goals_dataframe() -> pl.DataFrame:
    """Create sample goals DataFrame for testing.

    Returns
    -------
    pl.DataFrame
        Sample goals DataFrame.
    """
    return pl.DataFrame(
        {
            "Investor_ID": ["INV001", "INV001", "INV002", "INV003"],
            "Investor_Type": ["Primary", "Primary", "Spouse", "Dependent"],
            "Goal_Category": ["Retirement", "Healthcare", "Travel", "Education"],
            "Goal_Amount": [1200000, 150000, 75000, 100000],
            "Goal_Priority": [1, 2, 3, 1],
            "Goal_Timeline": [15, 10, 5, 35],
            "Goal_Description": [
                "Comfortable retirement",
                "Long-term care",
                "World travel",
                "College fund",
            ],
        },
    )


def create_sample_income_dataframe() -> pl.DataFrame:
    """Create sample income DataFrame for testing.

    Returns
    -------
    pl.DataFrame
        Sample income DataFrame.
    """
    return pl.DataFrame(
        {
            "Investor_ID": ["INV001", "INV001", "INV002", "INV002"],
            "Investor_Type": ["Primary", "Primary", "Spouse", "Spouse"],
            "Income_Category": ["Social Security", "Pension", "Social Security", "Part-time Work"],
            "Income_Annual": [28000, 45000, 22000, 15000],
            "Income_Start_Age": [67, 65, 65, 62],
            "Income_End_Age": [95, 95, 95, 70],
            "Income_Source": ["Government", "Former Employer", "Government", "Consulting"],
        },
    )


# =========================================================================
# Typst compilation
# =========================================================================


def compile_typst_report(
    typ_template_path: Path,
    output_pdf_path: Path,
) -> tuple[bool, str]:
    """Compile a Typst template to PDF.

    The template is expected to read its data from JSON files and SVG images
    via relative paths (``json("client_info.json")``, ``image(...)``).  All
    required files are copied into an ephemeral working directory so that
    Typst can resolve them.

    Parameters
    ----------
    typ_template_path : Path
        Absolute path to the ``.typ`` template.
    output_pdf_path : Path
        Desired path for the compiled PDF.

    Returns
    -------
    tuple[bool, str]
        ``(success, message)``.
    """
    if not typ_template_path.exists():
        return False, f"Typst template not found: {typ_template_path}"

    tmp_dir: Path | None = None
    try:
        output_pdf_path.parent.mkdir(parents=True, exist_ok=True)
        tmp_dir = Path(tempfile.mkdtemp(prefix="qwim_typst_"))

        template_dir = typ_template_path.parent

        # Copy the template itself
        shutil.copy2(typ_template_path, tmp_dir / typ_template_path.name)

        # Copy JSON files next to template
        for json_src in [
            template_dir / "client_info.json",
            template_dir / "report_metadata.json",
        ]:
            if json_src.exists():
                shutil.copy2(json_src, tmp_dir / json_src.name)

        # Copy JSON subdirectories
        for subdir_name in ("inputs_json", "outputs_json"):
            src_dir = template_dir / subdir_name
            if src_dir.is_dir():
                dst_dir = tmp_dir / subdir_name
                dst_dir.mkdir(exist_ok=True)
                for f in src_dir.iterdir():
                    if f.is_file():
                        shutil.copy2(f, dst_dir / f.name)

        # Copy SVG images
        img_src = template_dir / "outputs_images"
        if img_src.is_dir():
            img_dst = tmp_dir / "outputs_images"
            img_dst.mkdir(exist_ok=True)
            for f in img_src.iterdir():
                if f.is_file():
                    shutil.copy2(f, img_dst / f.name)

        # Copy any other assets (bib, fonts, etc.)
        for candidate in template_dir.iterdir():
            if candidate.is_file() and candidate.suffix in {
                ".bib",
                ".png",
                ".jpg",
                ".jpeg",
            }:
                dest = tmp_dir / candidate.name
                if not dest.exists():
                    shutil.copy2(candidate, dest)

        # Ensure bibliography stub exists
        bib_path = tmp_dir / "sample_refs.bib"
        if not bib_path.exists():
            bib_path.write_text("% Empty bibliography\n", encoding="utf-8")

        tmp_typ = tmp_dir / typ_template_path.name

        # Compile via typst Python package or CLI subprocess
        compiled = False
        compile_error = ""
        try:
            import typst as _typst

            _typst.compile(str(tmp_typ), output=str(output_pdf_path))
            compiled = True
        except ImportError:
            pass
        except Exception as typst_pkg_error:
            compile_error = str(typst_pkg_error)

        if not compiled:
            try:
                result = subprocess.run(
                    ["typst", "compile", str(tmp_typ), str(output_pdf_path)],
                    capture_output=True,
                    text=True,
                    timeout=120,
                    check=False,
                )
                if result.returncode == 0:
                    compiled = True
                else:
                    compile_error = result.stderr or result.stdout
            except FileNotFoundError:
                compile_error = (
                    "typst CLI not found. Install via `pip install typst` "
                    "or download from https://typst.app"
                )
            except subprocess.TimeoutExpired:
                compile_error = "Typst compilation timed out after 120 seconds"

        if not compiled:
            return False, f"Typst compilation failed: {compile_error}"

        if not output_pdf_path.exists():
            return False, "Compilation appeared to succeed but PDF not found"

        file_size = output_pdf_path.stat().st_size
        if file_size == 0:
            return False, "Compiled PDF is empty (0 bytes)"

        return True, f"Typst PDF compiled successfully ({file_size:,} bytes)"

    except Exception as exc:
        return False, f"Unexpected error during Typst compilation: {exc}"
    finally:
        if tmp_dir and tmp_dir.exists():
            shutil.rmtree(tmp_dir, ignore_errors=True)


# =========================================================================
# Main entry point
# =========================================================================


def generate_report_PDF(
    report_title: str = "QWIM Portfolio and Investor Analysis Report",
    output_filename: str = "qwim_report.pdf",
    output_directory: str = "outputs/reports",
    reactives_shiny: dict | None = None,
    user_id: str = "default_user",
    include_charts: bool = True,
    chart_resolution: str = "high",
) -> tuple[bool, str, str]:
    """Generate a QWIM PDF report using the Typst typesetting pipeline.

    Orchestrates:
    1. JSON data export (client info, subtab inputs/outputs)
    2. SVG chart generation via plotnine (when *include_charts* is ``True``)
    3. Typst template compilation to PDF

    Parameters
    ----------
    report_title : str
        Human-readable title (decorative — title is set in the template).
    output_filename : str
        Desired PDF filename including ``.pdf`` extension.
    output_directory : str
        Target directory for the output PDF.
    reactives_shiny : dict | None
        Shared reactive state dictionary from the Shiny application.
    user_id : str
        User identifier for logging.
    include_charts : bool
        Whether to generate SVG charts via plotnine.
    chart_resolution : str
        Reserved for future use.

    Returns
    -------
    tuple[bool, str, str]
        ``(success_flag, status_message, pdf_file_path)``.
    """
    logger.info("=" * 70)
    logger.info("PDF REPORT GENERATION  user: %s", user_id)
    logger.info("  title    : %s", report_title)
    logger.info("  filename : %s", output_filename)
    logger.info("  directory: %s", output_directory)
    logger.info("=" * 70)

    # Input validation
    if not output_filename or not output_filename.strip():
        msg = "output_filename cannot be empty"
        logger.error(msg)
        return False, msg, ""

    if not output_filename.lower().endswith(".pdf"):
        output_filename = output_filename + ".pdf"

    # Locate Typst template
    typ_template = _REPORTING_DIR / "report_QWIM.typ"
    if not typ_template.exists():
        msg = f"Typst template not found at: {typ_template}"
        logger.error(msg)
        return False, msg, ""

    # Prepare output path
    output_dir = Path(output_directory)
    try:
        output_dir.mkdir(parents=True, exist_ok=True)
    except Exception as dir_error:
        msg = f"Cannot create output directory '{output_dir}': {dir_error}"
        logger.error(msg)
        return False, msg, ""

    output_pdf = output_dir / output_filename

    # --- Step 1: Export data to JSON ---
    try:
        export_all_report_data(reactives_shiny)
        logger.info("JSON data export completed")
    except Exception as data_error:
        msg = f"Failed to export report data: {data_error}"
        logger.error(msg)
        return False, msg, ""

    # --- Step 2: Generate SVG charts ---
    if include_charts:
        try:
            export_all_report_plots(reactives_shiny)
            logger.info("SVG chart export completed")
        except Exception as plot_error:
            logger.warning("Chart export failed (continuing without charts): %s", plot_error)

    # --- Step 3: Compile Typst ---
    success, compile_msg = compile_typst_report(typ_template, output_pdf)
    if success:
        abs_path = str(output_pdf.resolve())
        logger.info("Report saved to %s", abs_path)
        return True, compile_msg, abs_path

    logger.error("Compilation failed: %s", compile_msg)
    return False, compile_msg, ""


# =========================================================================
# Smoke test
# =========================================================================


def test_report_generation() -> tuple[bool, str]:
    """Smoke-test PDF report generation with sample data.

    Returns
    -------
    tuple[bool, str]
        ``(success_flag, message)``.
    """
    try:
        logger.info("Testing report generation with sample data...")
        timestamp = datetime.datetime.now(datetime.UTC).strftime("%Y%m%d_%H%M%S")
        success, message, file_path = generate_report_PDF(
            report_title="Test QWIM Report",
            output_filename=f"test_report_{timestamp}.pdf",
            output_directory="outputs/test",
            reactives_shiny=None,
            user_id="test_user",
        )
        if success:
            return True, f"Test passed: {message}  {file_path}"
        return False, f"Test failed: {message}"
    except Exception as test_error:
        return False, f"Test error: {test_error}"


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    logger.info("QWIM PDF Report Generator — Test Mode")
    ok, msg = test_report_generation()
    status = "PASSED" if ok else "FAILED"
    logger.info("TEST %s: %s", status, msg)
