"""Regression tests for covariance and correlation estimation methods.

These tests verify that covariance/correlation matrix outputs from
``utils_cov_corr.py`` do not change unexpectedly across code changes,
package upgrades, or refactors.

Test Strategy
-------------
Each test:
1. Loads a pre-computed baseline Parquet file (generated by ``generate_baselines.py``).
2. Re-computes the same output with identical fixed-seed input data.
3. Compares every value against the baseline within the stated tolerance.

Tolerances
----------
* Deterministic estimators (Empirical, Shrunk, OAS, Ledoit-Wolf):
  tolerance = 1e-10.
* Stochastic or numerically sensitive estimators (EW):
  tolerance = 1e-8.

Baseline Regeneration
---------------------
If a test fails because of an *intentional* algorithmic change::

    python tests/regression_data/covariance/generate_baselines.py

Then commit both the code changes and the updated Parquet files together.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np
import polars as pl
import pytest


if TYPE_CHECKING:
    from src.num_methods.covariance.utils_cov_corr import covariance_matrix

from tests.tests_regression.num_methods.covariance.conftest import (  # pyright: ignore[reportMissingImports]
    COMPONENT_NAMES_3,
    COMPONENT_NAMES_5,
    load_baseline,
)


# ---------------------------------------------------------------------------
# Tolerances
# ---------------------------------------------------------------------------
_TOL_DETERMINISTIC: float = 1e-10
_TOL_NUMERICAL: float = 1e-8


# =============================================================================
# Helper
# =============================================================================


def _assert_matrix_matches_baseline(
    current: np.ndarray,
    baseline_df: pl.DataFrame,
    component_names: list[str],
    *,
    tolerance: float = _TOL_DETERMINISTIC,
    label: str = "",
) -> None:
    """Compare a numpy matrix against a baseline Parquet DataFrame.

    Parameters
    ----------
    current:
        Matrix produced by re-running the estimator in this test session.
    baseline_df:
        DataFrame loaded from the Parquet baseline file.
    component_names:
        Column names matching matrix columns.
    tolerance:
        Absolute tolerance for numeric comparisons.
    label:
        Optional label used in error messages.

    Raises
    ------
    AssertionError
        If shapes differ or any numeric value deviates beyond ``tolerance``.
    """
    num_rows, num_cols = current.shape
    assert num_rows == len(baseline_df), (
        f"Row count mismatch {label}: current={num_rows}, baseline={len(baseline_df)}"
    )
    assert num_cols == len(component_names), (
        f"Column count mismatch {label}: current={num_cols}, expected={len(component_names)}"
    )

    mismatches: list[str] = []
    for idx_col, col_name in enumerate(component_names):
        baseline_col = baseline_df[col_name].to_list()
        for idx_row in range(num_rows):
            c_val = float(current[idx_row, idx_col])
            b_val = float(baseline_col[idx_row])
            diff = abs(c_val - b_val)
            if diff > tolerance:
                mismatches.append(
                    f"  [{idx_row},{idx_col}] {col_name}: "
                    f"baseline={b_val:.12e}  current={c_val:.12e}  diff={diff:.2e}",
                )

    assert not mismatches, f"Regression failure {label} (tolerance={tolerance:.2e}):\n" + "\n".join(
        mismatches
    )


def _assert_dataframe_matches_baseline(
    current: pl.DataFrame,
    baseline: pl.DataFrame,
    *,
    tolerance: float = _TOL_DETERMINISTIC,
    label: str = "",
) -> None:
    """Compare two Polars DataFrames element-by-element within tolerance.

    Parameters
    ----------
    current:
        DataFrame produced by re-running the model in this test session.
    baseline:
        DataFrame loaded from the Parquet baseline file.
    tolerance:
        Absolute tolerance for numeric comparisons.
    label:
        Optional label used in error messages.

    Raises
    ------
    AssertionError
        If shapes differ or any numeric value deviates beyond ``tolerance``.
    """
    assert current.shape == baseline.shape, (
        f"Shape mismatch {label}: current={current.shape}, baseline={baseline.shape}"
    )
    assert current.columns == baseline.columns, (
        f"Column mismatch {label}: current={current.columns}, baseline={baseline.columns}"
    )

    mismatches: list[str] = []
    for col in current.columns:
        if current[col].dtype in (pl.Float32, pl.Float64):
            for idx_row in range(len(current)):
                c_val = float(current[col][idx_row])
                b_val = float(baseline[col][idx_row])
                diff = abs(c_val - b_val)
                if diff > tolerance:
                    mismatches.append(
                        f"  [{idx_row}] {col}: baseline={b_val:.12e}  "
                        f"current={c_val:.12e}  diff={diff:.2e}",
                    )

    assert not mismatches, f"Regression failure {label} (tolerance={tolerance:.2e}):\n" + "\n".join(
        mismatches
    )


# =============================================================================
# Regression tests - EMPIRICAL estimator (3 assets)
# =============================================================================


@pytest.mark.regression()
class Class_Test_Regression_Covariance_Empirical_3_Assets:
    """Regression: EMPIRICAL covariance estimator on 3-asset canonical data."""

    def Test_Covariance_Matrix_Matches_Baseline(
        self,
        fitted_empirical_3: covariance_matrix,
    ) -> None:
        """Empirical covariance matrix must match stored baseline."""
        baseline = load_baseline("cov_empirical_3_assets")
        _assert_matrix_matches_baseline(
            fitted_empirical_3.get_covariance_matrix(),
            baseline,
            COMPONENT_NAMES_3,
            label="cov_empirical_3_assets",
        )

    def Test_Correlation_Matrix_Matches_Baseline(
        self,
        fitted_empirical_3: covariance_matrix,
    ) -> None:
        """Empirical correlation matrix must match stored baseline."""
        baseline = load_baseline("corr_empirical_3_assets")
        _assert_matrix_matches_baseline(
            fitted_empirical_3.get_correlation_matrix(),
            baseline,
            COMPONENT_NAMES_3,
            label="corr_empirical_3_assets",
        )

    def Test_Matrix_Shape_Is_3x3(
        self,
        fitted_empirical_3: covariance_matrix,
    ) -> None:
        """Empirical covariance matrix must be 3x3."""
        assert fitted_empirical_3.m_cov_matrix.shape == (3, 3)

    def Test_Num_Components_Is_3(
        self,
        fitted_empirical_3: covariance_matrix,
    ) -> None:
        """Model must report exactly 3 components."""
        assert fitted_empirical_3.m_num_components == 3

    def Test_Num_Observations_Is_200(
        self,
        fitted_empirical_3: covariance_matrix,
    ) -> None:
        """Model must report exactly 200 observations."""
        assert fitted_empirical_3.m_num_observations == 200

    def Test_Component_Names_Match(
        self,
        fitted_empirical_3: covariance_matrix,
    ) -> None:
        """Component names must match canonical order."""
        assert fitted_empirical_3.m_component_names == COMPONENT_NAMES_3

    def Test_Component_Variances_Match_Baseline(
        self,
        fitted_empirical_3: covariance_matrix,
    ) -> None:
        """Individual component variances must match baseline."""
        baseline = load_baseline("component_variances_empirical_3_assets")
        for idx_row in range(len(baseline)):
            comp_name = str(baseline["Component"][idx_row])
            expected_var = float(baseline["Variance"][idx_row])
            actual_var = fitted_empirical_3.get_component_variance(comp_name)
            assert actual_var == pytest.approx(expected_var, abs=_TOL_DETERMINISTIC), (
                f"Variance mismatch for {comp_name}: "
                f"expected={expected_var:.12e}, actual={actual_var:.12e}"
            )

    def Test_Component_Covariances_Match_Baseline(
        self,
        fitted_empirical_3: covariance_matrix,
    ) -> None:
        """Pairwise component covariances must match baseline."""
        baseline = load_baseline("component_covariances_empirical_3_assets")
        for idx_row in range(len(baseline)):
            comp_1 = str(baseline["Component_1"][idx_row])
            comp_2 = str(baseline["Component_2"][idx_row])
            expected_cov = float(baseline["Covariance"][idx_row])
            actual_cov = fitted_empirical_3.get_component_covariance(comp_1, comp_2)
            assert actual_cov == pytest.approx(expected_cov, abs=_TOL_DETERMINISTIC), (
                f"Covariance mismatch ({comp_1}, {comp_2}): "
                f"expected={expected_cov:.12e}, actual={actual_cov:.12e}"
            )

    def Test_Metadata_Matches_Baseline(
        self,
        fitted_empirical_3: covariance_matrix,
    ) -> None:
        """Model metadata must match baseline."""
        baseline = load_baseline("metadata_empirical_3_assets")
        assert fitted_empirical_3.m_estimator_type.value == str(baseline["Estimator"][0])
        assert fitted_empirical_3.m_num_components == int(baseline["Num_Components"][0])
        assert fitted_empirical_3.m_num_observations == int(baseline["Num_Observations"][0])

    def Test_Matrix_Symmetry_Preserved(
        self,
        fitted_empirical_3: covariance_matrix,
    ) -> None:
        """Covariance matrix must remain symmetric after re-estimation."""
        cov = fitted_empirical_3.get_covariance_matrix()
        np.testing.assert_allclose(cov, cov.T, atol=1e-12)

    def Test_Positive_Semidefinite_Property(
        self,
        fitted_empirical_3: covariance_matrix,
    ) -> None:
        """All eigenvalues must be non-negative."""
        eigenvalues = np.linalg.eigvals(fitted_empirical_3.get_covariance_matrix())
        assert np.all(eigenvalues.real >= -1e-12)

    def Test_Correlation_Diagonal_Is_Unity(
        self,
        fitted_empirical_3: covariance_matrix,
    ) -> None:
        """Correlation matrix diagonal must be exactly 1.0."""
        corr = fitted_empirical_3.get_correlation_matrix()
        np.testing.assert_allclose(np.diag(corr), 1.0, atol=1e-10)

    def Test_Correlation_Values_In_Valid_Range(
        self,
        fitted_empirical_3: covariance_matrix,
    ) -> None:
        """All correlation values must be in [-1, 1]."""
        corr = fitted_empirical_3.get_correlation_matrix()
        assert np.all(corr >= -1.0 - 1e-10)
        assert np.all(corr <= 1.0 + 1e-10)


# =============================================================================
# Regression tests - LEDOIT_WOLF estimator (3 assets)
# =============================================================================


@pytest.mark.regression()
class Class_Test_Regression_Covariance_Ledoit_Wolf_3_Assets:
    """Regression: LEDOIT_WOLF shrinkage estimator on 3-asset canonical data."""

    def Test_Covariance_Matrix_Matches_Baseline(
        self,
        fitted_ledoit_wolf_3: covariance_matrix,
    ) -> None:
        """Ledoit-Wolf covariance must match stored baseline."""
        baseline = load_baseline("cov_ledoit_wolf_3_assets")
        _assert_matrix_matches_baseline(
            fitted_ledoit_wolf_3.get_covariance_matrix(),
            baseline,
            COMPONENT_NAMES_3,
            label="cov_ledoit_wolf_3_assets",
        )

    def Test_Correlation_Matrix_Matches_Baseline(
        self,
        fitted_ledoit_wolf_3: covariance_matrix,
    ) -> None:
        """Ledoit-Wolf correlation must match stored baseline."""
        baseline = load_baseline("corr_ledoit_wolf_3_assets")
        _assert_matrix_matches_baseline(
            fitted_ledoit_wolf_3.get_correlation_matrix(),
            baseline,
            COMPONENT_NAMES_3,
            label="corr_ledoit_wolf_3_assets",
        )

    def Test_Shrinkage_Differs_From_Empirical(
        self,
        fitted_ledoit_wolf_3: covariance_matrix,
        fitted_empirical_3: covariance_matrix,
    ) -> None:
        """Ledoit-Wolf should differ from pure empirical due to shrinkage."""
        cov_lw = fitted_ledoit_wolf_3.get_covariance_matrix()
        cov_emp = fitted_empirical_3.get_covariance_matrix()
        assert not np.allclose(cov_lw, cov_emp, atol=1e-12), (
            "Ledoit-Wolf and Empirical should differ"
        )

    def Test_Matrix_Symmetry_Preserved(
        self,
        fitted_ledoit_wolf_3: covariance_matrix,
    ) -> None:
        """Ledoit-Wolf covariance must be symmetric."""
        cov = fitted_ledoit_wolf_3.get_covariance_matrix()
        np.testing.assert_allclose(cov, cov.T, atol=1e-12)

    def Test_Positive_Semidefinite_Property(
        self,
        fitted_ledoit_wolf_3: covariance_matrix,
    ) -> None:
        """All eigenvalues must be non-negative."""
        eigenvalues = np.linalg.eigvals(fitted_ledoit_wolf_3.get_covariance_matrix())
        assert np.all(eigenvalues.real >= -1e-12)


# =============================================================================
# Regression tests - OAS estimator (3 assets)
# =============================================================================


@pytest.mark.regression()
class Class_Test_Regression_Covariance_OAS_3_Assets:
    """Regression: Oracle Approximating Shrinkage estimator on 3-asset data."""

    def Test_Covariance_Matrix_Matches_Baseline(
        self,
        fitted_oas_3: covariance_matrix,
    ) -> None:
        """OAS covariance must match stored baseline."""
        baseline = load_baseline("cov_oas_3_assets")
        _assert_matrix_matches_baseline(
            fitted_oas_3.get_covariance_matrix(),
            baseline,
            COMPONENT_NAMES_3,
            label="cov_oas_3_assets",
        )

    def Test_Correlation_Matrix_Matches_Baseline(
        self,
        fitted_oas_3: covariance_matrix,
    ) -> None:
        """OAS correlation must match stored baseline."""
        baseline = load_baseline("corr_oas_3_assets")
        _assert_matrix_matches_baseline(
            fitted_oas_3.get_correlation_matrix(),
            baseline,
            COMPONENT_NAMES_3,
            label="corr_oas_3_assets",
        )

    def Test_Matrix_Symmetry_Preserved(
        self,
        fitted_oas_3: covariance_matrix,
    ) -> None:
        """OAS covariance must be symmetric."""
        cov = fitted_oas_3.get_covariance_matrix()
        np.testing.assert_allclose(cov, cov.T, atol=1e-12)


# =============================================================================
# Regression tests - SHRUNK_COVARIANCE estimator (3 assets)
# =============================================================================


@pytest.mark.regression()
class Class_Test_Regression_Covariance_Shrunk_3_Assets:
    """Regression: Shrunk covariance estimator on 3-asset canonical data."""

    def Test_Covariance_Matrix_Matches_Baseline(
        self,
        fitted_shrunk_3: covariance_matrix,
    ) -> None:
        """Shrunk covariance must match stored baseline."""
        baseline = load_baseline("cov_shrunk_3_assets")
        _assert_matrix_matches_baseline(
            fitted_shrunk_3.get_covariance_matrix(),
            baseline,
            COMPONENT_NAMES_3,
            label="cov_shrunk_3_assets",
        )

    def Test_Correlation_Matrix_Matches_Baseline(
        self,
        fitted_shrunk_3: covariance_matrix,
    ) -> None:
        """Shrunk correlation must match stored baseline."""
        baseline = load_baseline("corr_shrunk_3_assets")
        _assert_matrix_matches_baseline(
            fitted_shrunk_3.get_correlation_matrix(),
            baseline,
            COMPONENT_NAMES_3,
            label="corr_shrunk_3_assets",
        )

    def Test_Matrix_Symmetry_Preserved(
        self,
        fitted_shrunk_3: covariance_matrix,
    ) -> None:
        """Shrunk covariance must be symmetric."""
        cov = fitted_shrunk_3.get_covariance_matrix()
        np.testing.assert_allclose(cov, cov.T, atol=1e-12)


# =============================================================================
# Regression tests - EXPONENTIALLY_WEIGHTED estimator (3 assets)
# =============================================================================


@pytest.mark.regression()
class Class_Test_Regression_Covariance_EW_3_Assets:
    """Regression: Exponentially Weighted covariance estimator on 3-asset data."""

    def Test_Covariance_Matrix_Matches_Baseline(
        self,
        fitted_ew_3: covariance_matrix,
    ) -> None:
        """EW covariance must match stored baseline."""
        baseline = load_baseline("cov_ew_3_assets")
        _assert_matrix_matches_baseline(
            fitted_ew_3.get_covariance_matrix(),
            baseline,
            COMPONENT_NAMES_3,
            tolerance=_TOL_NUMERICAL,
            label="cov_ew_3_assets",
        )

    def Test_Correlation_Matrix_Matches_Baseline(
        self,
        fitted_ew_3: covariance_matrix,
    ) -> None:
        """EW correlation must match stored baseline."""
        baseline = load_baseline("corr_ew_3_assets")
        _assert_matrix_matches_baseline(
            fitted_ew_3.get_correlation_matrix(),
            baseline,
            COMPONENT_NAMES_3,
            tolerance=_TOL_NUMERICAL,
            label="corr_ew_3_assets",
        )

    def Test_Matrix_Symmetry_Preserved(
        self,
        fitted_ew_3: covariance_matrix,
    ) -> None:
        """EW covariance must be symmetric."""
        cov = fitted_ew_3.get_covariance_matrix()
        np.testing.assert_allclose(cov, cov.T, atol=1e-10)


# =============================================================================
# Regression tests - EMPIRICAL estimator (5 assets)
# =============================================================================


@pytest.mark.regression()
class Class_Test_Regression_Covariance_Empirical_5_Assets:
    """Regression: EMPIRICAL covariance estimator on 5-asset canonical data."""

    def Test_Covariance_Matrix_Matches_Baseline(
        self,
        fitted_empirical_5: covariance_matrix,
    ) -> None:
        """Empirical 5-asset covariance must match stored baseline."""
        baseline = load_baseline("cov_empirical_5_assets")
        _assert_matrix_matches_baseline(
            fitted_empirical_5.get_covariance_matrix(),
            baseline,
            COMPONENT_NAMES_5,
            label="cov_empirical_5_assets",
        )

    def Test_Correlation_Matrix_Matches_Baseline(
        self,
        fitted_empirical_5: covariance_matrix,
    ) -> None:
        """Empirical 5-asset correlation must match stored baseline."""
        baseline = load_baseline("corr_empirical_5_assets")
        _assert_matrix_matches_baseline(
            fitted_empirical_5.get_correlation_matrix(),
            baseline,
            COMPONENT_NAMES_5,
            label="corr_empirical_5_assets",
        )

    def Test_Matrix_Shape_Is_5x5(
        self,
        fitted_empirical_5: covariance_matrix,
    ) -> None:
        """Empirical 5-asset matrix must be 5x5."""
        assert fitted_empirical_5.m_cov_matrix.shape == (5, 5)

    def Test_Num_Components_Is_5(
        self,
        fitted_empirical_5: covariance_matrix,
    ) -> None:
        """Model must report exactly 5 components."""
        assert fitted_empirical_5.m_num_components == 5

    def Test_Num_Observations_Is_300(
        self,
        fitted_empirical_5: covariance_matrix,
    ) -> None:
        """Model must report exactly 300 observations."""
        assert fitted_empirical_5.m_num_observations == 300

    def Test_Component_Names_Match(
        self,
        fitted_empirical_5: covariance_matrix,
    ) -> None:
        """Component names must match canonical order."""
        assert fitted_empirical_5.m_component_names == COMPONENT_NAMES_5

    def Test_Matrix_Symmetry_Preserved(
        self,
        fitted_empirical_5: covariance_matrix,
    ) -> None:
        """5-asset covariance must be symmetric."""
        cov = fitted_empirical_5.get_covariance_matrix()
        np.testing.assert_allclose(cov, cov.T, atol=1e-12)

    def Test_Positive_Semidefinite_Property(
        self,
        fitted_empirical_5: covariance_matrix,
    ) -> None:
        """All eigenvalues must be non-negative for 5-asset matrix."""
        eigenvalues = np.linalg.eigvals(fitted_empirical_5.get_covariance_matrix())
        assert np.all(eigenvalues.real >= -1e-12)

    def Test_Correlation_Diagonal_Is_Unity(
        self,
        fitted_empirical_5: covariance_matrix,
    ) -> None:
        """5-asset correlation diagonal must be 1.0."""
        corr = fitted_empirical_5.get_correlation_matrix()
        np.testing.assert_allclose(np.diag(corr), 1.0, atol=1e-10)


# =============================================================================
# Regression tests - LEDOIT_WOLF estimator (5 assets)
# =============================================================================


@pytest.mark.regression()
class Class_Test_Regression_Covariance_Ledoit_Wolf_5_Assets:
    """Regression: LEDOIT_WOLF shrinkage estimator on 5-asset canonical data."""

    def Test_Covariance_Matrix_Matches_Baseline(
        self,
        fitted_ledoit_wolf_5: covariance_matrix,
    ) -> None:
        """Ledoit-Wolf 5-asset covariance must match stored baseline."""
        baseline = load_baseline("cov_ledoit_wolf_5_assets")
        _assert_matrix_matches_baseline(
            fitted_ledoit_wolf_5.get_covariance_matrix(),
            baseline,
            COMPONENT_NAMES_5,
            label="cov_ledoit_wolf_5_assets",
        )

    def Test_Correlation_Matrix_Matches_Baseline(
        self,
        fitted_ledoit_wolf_5: covariance_matrix,
    ) -> None:
        """Ledoit-Wolf 5-asset correlation must match stored baseline."""
        baseline = load_baseline("corr_ledoit_wolf_5_assets")
        _assert_matrix_matches_baseline(
            fitted_ledoit_wolf_5.get_correlation_matrix(),
            baseline,
            COMPONENT_NAMES_5,
            label="corr_ledoit_wolf_5_assets",
        )

    def Test_Shrinkage_Differs_From_Empirical(
        self,
        fitted_ledoit_wolf_5: covariance_matrix,
        fitted_empirical_5: covariance_matrix,
    ) -> None:
        """Ledoit-Wolf 5-asset should differ from empirical."""
        cov_lw = fitted_ledoit_wolf_5.get_covariance_matrix()
        cov_emp = fitted_empirical_5.get_covariance_matrix()
        assert not np.allclose(cov_lw, cov_emp, atol=1e-12)

    def Test_Matrix_Symmetry_Preserved(
        self,
        fitted_ledoit_wolf_5: covariance_matrix,
    ) -> None:
        """Ledoit-Wolf 5-asset covariance must be symmetric."""
        cov = fitted_ledoit_wolf_5.get_covariance_matrix()
        np.testing.assert_allclose(cov, cov.T, atol=1e-12)

    def Test_Positive_Semidefinite_Property(
        self,
        fitted_ledoit_wolf_5: covariance_matrix,
    ) -> None:
        """All eigenvalues must be non-negative."""
        eigenvalues = np.linalg.eigvals(fitted_ledoit_wolf_5.get_covariance_matrix())
        assert np.all(eigenvalues.real >= -1e-12)


# =============================================================================
# Cross-estimator regression tests
# =============================================================================


@pytest.mark.regression()
class Class_Test_Regression_Cross_Estimator_Consistency:
    """Regression: cross-estimator relationships that must hold."""

    def Test_All_3_Asset_Estimators_Same_Dimensions(
        self,
        fitted_empirical_3: covariance_matrix,
        fitted_ledoit_wolf_3: covariance_matrix,
        fitted_oas_3: covariance_matrix,
        fitted_shrunk_3: covariance_matrix,
        fitted_ew_3: covariance_matrix,
    ) -> None:
        """All 3-asset estimators must produce (3,3) matrices."""
        for estimator_obj in [
            fitted_empirical_3,
            fitted_ledoit_wolf_3,
            fitted_oas_3,
            fitted_shrunk_3,
            fitted_ew_3,
        ]:
            assert estimator_obj.m_cov_matrix.shape == (3, 3)

    def Test_All_3_Asset_Estimators_Same_Component_Names(
        self,
        fitted_empirical_3: covariance_matrix,
        fitted_ledoit_wolf_3: covariance_matrix,
        fitted_oas_3: covariance_matrix,
        fitted_shrunk_3: covariance_matrix,
        fitted_ew_3: covariance_matrix,
    ) -> None:
        """All 3-asset estimators must report same component names."""
        for estimator_obj in [
            fitted_ledoit_wolf_3,
            fitted_oas_3,
            fitted_shrunk_3,
            fitted_ew_3,
        ]:
            assert estimator_obj.m_component_names == fitted_empirical_3.m_component_names

    def Test_All_Estimators_Positive_Diagonal(
        self,
        fitted_empirical_3: covariance_matrix,
        fitted_ledoit_wolf_3: covariance_matrix,
        fitted_oas_3: covariance_matrix,
        fitted_shrunk_3: covariance_matrix,
        fitted_ew_3: covariance_matrix,
    ) -> None:
        """All estimator diagonals (variances) must be positive."""
        for estimator_obj in [
            fitted_empirical_3,
            fitted_ledoit_wolf_3,
            fitted_oas_3,
            fitted_shrunk_3,
            fitted_ew_3,
        ]:
            diag = np.diag(estimator_obj.get_covariance_matrix())
            assert np.all(diag > 0), f"Non-positive diagonal for {estimator_obj.m_estimator_type}"

    def Test_Shrinkage_Reduces_Extreme_Correlations(
        self,
        fitted_empirical_3: covariance_matrix,
        fitted_ledoit_wolf_3: covariance_matrix,
    ) -> None:
        """Shrinkage should pull extreme correlations toward zero.

        The off-diagonal range of Ledoit-Wolf correlations should be
        equal to or narrower than empirical correlations.
        """
        corr_emp = fitted_empirical_3.get_correlation_matrix()
        corr_lw = fitted_ledoit_wolf_3.get_correlation_matrix()

        # Compare off-diagonal range
        np.fill_diagonal(corr_emp, 0.0)
        np.fill_diagonal(corr_lw, 0.0)

        range_emp = np.max(np.abs(corr_emp))
        range_lw = np.max(np.abs(corr_lw))

        assert range_lw <= range_emp + 1e-10, (
            f"Shrinkage should reduce extremes: emp_range={range_emp:.6f}, lw_range={range_lw:.6f}"
        )

    def Test_Covariance_Self_Equals_Variance_All_Estimators(
        self,
        fitted_empirical_3: covariance_matrix,
        fitted_ledoit_wolf_3: covariance_matrix,
    ) -> None:
        """cov(A, A) must equal variance(A) for all estimators."""
        for estimator_obj in [fitted_empirical_3, fitted_ledoit_wolf_3]:
            for comp_name in estimator_obj.m_component_names:
                cov_self = estimator_obj.get_component_covariance(comp_name, comp_name)
                var_comp = estimator_obj.get_component_variance(comp_name)
                assert cov_self == pytest.approx(var_comp, abs=1e-15)


# =============================================================================
# Input data regression tests
# =============================================================================


@pytest.mark.regression()
class Class_Test_Regression_Canonical_Input_Data:
    """Regression: verify canonical input data has not changed."""

    def Test_3_Asset_Returns_Match_Baseline(
        self,
        canonical_returns_3_assets: pl.DataFrame,
    ) -> None:
        """Canonical 3-asset returns must exactly match stored baseline."""
        baseline = load_baseline("canonical_returns_3_assets")
        assert canonical_returns_3_assets.shape == baseline.shape

        for col in ["AAPL", "MSFT", "GOOG"]:
            for idx_row in range(len(canonical_returns_3_assets)):
                c_val = float(canonical_returns_3_assets[col][idx_row])
                b_val = float(baseline[col][idx_row])
                assert c_val == pytest.approx(b_val, abs=1e-15), (
                    f"3-asset returns mismatch at row {idx_row}, col {col}"
                )

    def Test_5_Asset_Returns_Match_Baseline(
        self,
        canonical_returns_5_assets: pl.DataFrame,
    ) -> None:
        """Canonical 5-asset returns must exactly match stored baseline."""
        baseline = load_baseline("canonical_returns_5_assets")
        assert canonical_returns_5_assets.shape == baseline.shape

        for col in COMPONENT_NAMES_5:
            for idx_row in range(len(canonical_returns_5_assets)):
                c_val = float(canonical_returns_5_assets[col][idx_row])
                b_val = float(baseline[col][idx_row])
                assert c_val == pytest.approx(b_val, abs=1e-15), (
                    f"5-asset returns mismatch at row {idx_row}, col {col}"
                )

    def Test_3_Asset_Returns_Shape(
        self,
        canonical_returns_3_assets: pl.DataFrame,
    ) -> None:
        """Canonical 3-asset data must have 200 rows x 4 columns."""
        assert canonical_returns_3_assets.shape == (200, 4)

    def Test_5_Asset_Returns_Shape(
        self,
        canonical_returns_5_assets: pl.DataFrame,
    ) -> None:
        """Canonical 5-asset data must have 300 rows x 6 columns."""
        assert canonical_returns_5_assets.shape == (300, 6)
