r"""Standard mean-reverting short-rate model (Vasicek / Ornstein-Uhlenbeck).

========================================================

Provides :class:`Interest_Rate_Model_Standard`, a stochastic model based
on the **Vasicek** (Ornstein-Uhlenbeck) short-rate process — the canonical
equilibrium term-structure model in the fixed-income literature.

The continuous-time specification is:

.. math::

    dr_t = \kappa (\theta - r_t)\, dt + \sigma\, dW_t

where :math:`\kappa > 0` is the mean-reversion speed, :math:`\theta`
is the long-run mean short rate, :math:`\sigma > 0` is the volatility,
and :math:`W_t` is a standard Brownian motion.

This is a Gaussian model; rates can in principle become negative, which
is empirically relevant for central-bank policy rates but may require
adjustment for nominal discount-rate applications.

Fitting
-------
Parameters are estimated from historical annual-rate data by an
**OLS regression on first differences** of the discretised OU process:

.. math::

    \Delta r_t = \alpha + \beta\, r_t + \varepsilon_t

so that :math:`\kappa = -\beta / \Delta t`, :math:`\theta = \alpha /
(-\beta)`, and :math:`\sigma = \mathrm{std}(\varepsilon) / \sqrt{\Delta t}`.

If the OLS estimate yields :math:`\hat\beta \ge 0` (non-mean-reverting
data), the model falls back to the constructor prior values.

Prediction
----------
Forward paths are generated by **exact simulation** of the OU process
(no Euler-Maruyama approximation error):

.. math::

    r_{t+\Delta t} = r_t e^{-\kappa\Delta t}
      + \theta(1 - e^{-\kappa\Delta t})
      + \sqrt{\frac{\sigma^2}{2\kappa}(1 - e^{-2\kappa\Delta t})}\,\varepsilon

The :class:`polars.DataFrame` returned by :meth:`predict` contains
per-period summary statistics across all Monte Carlo paths.

References
----------
* Vasicek, O. (1977). *An equilibrium characterization of the term
  structure.* Journal of Financial Economics, 5(2), 177-188.
* Brigo, D. & Mercurio, F. (2006). *Interest Rate Models — Theory and
  Practice.* Springer Finance.
* Hull, J. (2022). *Options, Futures, and Other Derivatives* (11th ed.).
  Pearson.

Author
------
QWIM Team

Version
-------
1.0.0 (2026-07-01)
"""

from __future__ import annotations

import numpy as np
import polars as pl

from numpy.linalg import lstsq

from src.models.interest_rate.model_interest_rate_base import (
    Interest_Rate_Model_Base,
    Interest_Rate_Model_Status,
)
from src.models.interest_rate.model_interest_rate_constant import _make_date_range
from src.utils.custom_exceptions_errors_loggers.exception_custom import (
    Exception_Validation_Input,
)
from src.utils.custom_exceptions_errors_loggers.logger_custom import get_logger


logger = get_logger(__name__)

# ======================================================================
# Module-level defaults
# ======================================================================

_DEFAULT_KAPPA: float = 0.3  # mean-reversion speed (yr^-1); moderate persistence
_DEFAULT_THETA: float = 0.04  # long-run mean short rate (4 %)
_DEFAULT_SIGMA: float = 0.015  # annual short-rate volatility (1.5 %)
_DEFAULT_N_SIMS: int = 1_000  # Monte Carlo paths


# ======================================================================
# Vasicek short-rate model
# ======================================================================


class Interest_Rate_Model_Standard(Interest_Rate_Model_Base):  # noqa: N801
    r"""Mean-reverting Vasicek short-rate model.

    Implements the Ornstein-Uhlenbeck process:

    .. math::

        dr_t = \kappa (\theta - r_t)\, dt + \sigma\, dW_t

    Parameters
    ----------
    kappa : float, optional
        Initial guess for mean-reversion speed :math:`\kappa > 0`
        (default ``0.3``).  Overwritten by :meth:`fit`.
    theta : float, optional
        Initial guess for long-run mean :math:`\theta` in decimal form
        (default ``0.04`` for 4 %).  Overwritten by :meth:`fit`.
    sigma : float, optional
        Initial guess for short-rate volatility :math:`\sigma > 0`
        (default ``0.015``).  Overwritten by :meth:`fit`.
    n_simulations : int, optional
        Number of Monte Carlo paths for :meth:`predict`
        (default ``1 000``).
    name_model : str, optional
        Human-readable label (default ``"Vasicek Interest Rate"``).

    Attributes
    ----------
    m_kappa : float
        Fitted mean-reversion speed.
    m_theta : float
        Fitted long-run mean short rate.
    m_sigma : float
        Fitted short-rate volatility.
    m_current_rate : float
        Last observed short rate (used as the simulation starting point).
    m_n_simulations : int
        Number of Monte Carlo paths.

    Notes
    -----
    Because the Vasicek model is Gaussian, negative rates are possible.
    For applications where non-negative rates are required, consider
    applying a floor at zero or using a CIR-type model.

    Examples
    --------
    >>> import polars as pl
    >>> import numpy as np
    >>> rng = np.random.default_rng(0)
    >>> dates = pl.date_range(
    ...     start=pl.date(2015, 1, 1),
    ...     end=pl.date(2024, 12, 1),
    ...     interval="1y",
    ...     eager=True,
    ... )
    >>> rates = 0.04 + 0.01 * rng.standard_normal(len(dates))
    >>> hist = pl.DataFrame({"Date": dates, "short_rate": rates})
    >>> model = Interest_Rate_Model_Standard(n_simulations=200)
    >>> model.fit(hist)  # doctest: +SKIP
    >>> df = model.predict(n_periods=12, start_date="2025-01-01", seed=42)
    >>> "Mean" in df.columns
    True
    """

    # ------------------------------------------------------------------
    # Construction
    # ------------------------------------------------------------------

    def __init__(
        self,
        kappa: float = _DEFAULT_KAPPA,
        theta: float = _DEFAULT_THETA,
        sigma: float = _DEFAULT_SIGMA,
        n_simulations: int = _DEFAULT_N_SIMS,
        name_model: str = "Vasicek Interest Rate",
    ) -> None:
        super().__init__(name_model=name_model)

        _validate_positive_float(kappa, "kappa")
        _validate_positive_float(sigma, "sigma")

        if not isinstance(theta, float | int) or not np.isfinite(theta):
            raise Exception_Validation_Input(
                "theta must be a finite number",
                field_name="theta",
                expected_type=float,
                actual_value=theta,
            )
        if not isinstance(n_simulations, int) or n_simulations < 1:
            raise Exception_Validation_Input(
                "n_simulations must be a positive integer",
                field_name="n_simulations",
                expected_type=int,
                actual_value=n_simulations,
            )

        self.m_kappa: float = float(kappa)
        self.m_theta: float = float(theta)
        self.m_sigma: float = float(sigma)
        self.m_n_simulations: int = n_simulations
        self.m_current_rate: float = float(theta)  # init to long-run mean

        logger.info(
            "Interest_Rate_Model_Standard constructed: "
            "kappa=%.4f, theta=%.4f, sigma=%.4f, n_sims=%d",
            self.m_kappa,
            self.m_theta,
            self.m_sigma,
            self.m_n_simulations,
        )

    # ------------------------------------------------------------------
    # Fit
    # ------------------------------------------------------------------

    def fit(self, data: pl.DataFrame) -> Interest_Rate_Model_Standard:
        r"""Estimate Vasicek parameters from historical short-rate data via OLS.

        The discrete-time OU process gives:

        .. math::

            \Delta r_t = \alpha + \beta\, r_t + \varepsilon_t

        which is fitted by OLS.  Parameters are recovered as:

        * :math:`\kappa = -\hat\beta / \Delta t`
        * :math:`\theta = \hat\alpha / (-\hat\beta)`
        * :math:`\sigma = \mathrm{std}(\hat\varepsilon) / \sqrt{\Delta t}`

        where :math:`\Delta t` is the median time step in years inferred
        from the ``"Date"`` column.

        Parameters
        ----------
        data : pl.DataFrame
            Historical data with columns ``"Date"``
            (:class:`polars.Date`) and ``"short_rate"``
            (:class:`polars.Float64`, annual decimal rates).
            Must contain at least 3 rows.

        Returns
        -------
        Interest_Rate_Model_Standard
            The fitted model instance (``self``).

        Raises
        ------
        Exception_Validation_Input
            If *data* is invalid, contains fewer than 3 rows, or
            contains non-finite values.
        """
        self._validate_rate_data(data)

        if len(data) < 3:
            raise Exception_Validation_Input(
                "data must have at least 3 rows to estimate Vasicek parameters",
                field_name="data",
                expected_type=pl.DataFrame,
                actual_value=len(data),
            )

        # Sort by date to ensure temporal order
        data = data.sort("Date")

        rates = data["short_rate"].to_numpy().astype(np.float64)

        if not np.all(np.isfinite(rates)):
            raise Exception_Validation_Input(
                "short_rate column contains non-finite values",
                field_name="short_rate",
                expected_type=float,
                actual_value="non-finite entry",
            )

        # Infer dt from median gap between dates (in years)
        dates = data["Date"].to_numpy().astype("datetime64[D]")
        gaps_days = np.diff(dates.astype(np.float64))
        dt = float(np.median(gaps_days)) / 365.25

        if dt <= 0:
            raise Exception_Validation_Input(
                "Dates are not strictly increasing or gap is zero",
                field_name="Date",
                expected_type=pl.Date,
                actual_value=dt,
            )

        # OLS: dr_t = alpha + beta * r_t
        y = np.diff(rates)  # dr_t = r_{t+1} - r_t
        x = rates[:-1]  # r_t

        a_mat = np.column_stack([np.ones(len(x)), x])
        coeffs, _residuals, *_ = lstsq(a_mat, y, rcond=None)
        alpha_ols, beta_ols = coeffs[0], coeffs[1]

        if beta_ols >= 0:
            logger.warning(
                "OLS beta=%.4f >= 0; Vasicek process may not be mean-reverting "
                "for these data. Falling back to constructor priors.",
                beta_ols,
            )
            kappa = self.m_kappa
            theta = self.m_theta
        else:
            kappa = -beta_ols / dt
            theta = alpha_ols / (-beta_ols)

        # Residual std -> sigma
        resid = y - (alpha_ols + beta_ols * x)
        sigma = float(np.std(resid, ddof=2)) / np.sqrt(dt) if len(resid) > 2 else self.m_sigma

        if not (np.isfinite(kappa) and np.isfinite(theta) and np.isfinite(sigma)):
            raise Exception_Validation_Input(
                "OLS produced non-finite parameter estimates; check data quality",
                field_name="data",
                expected_type=pl.DataFrame,
                actual_value="non-finite OLS result",
            )

        self.m_kappa = float(kappa)
        self.m_theta = float(theta)
        self.m_sigma = float(sigma)
        self.m_current_rate = float(rates[-1])
        self.m_status = Interest_Rate_Model_Status.FITTED  # type: ignore[reportAttributeAccessIssue]

        self.m_parameters = {
            "kappa": self.m_kappa,
            "theta": self.m_theta,
            "sigma": self.m_sigma,
            "current_rate": self.m_current_rate,
            "dt_years": dt,
        }

        logger.info(
            "Interest_Rate_Model_Standard fitted: kappa=%.4f, theta=%.4f, "
            "sigma=%.4f, current_rate=%.4f (n=%d, dt=%.4f yr)",
            self.m_kappa,
            self.m_theta,
            self.m_sigma,
            self.m_current_rate,
            len(rates),
            dt,
        )

        return self

    # ------------------------------------------------------------------
    # Predict
    # ------------------------------------------------------------------

    def predict(
        self,
        n_periods: int,
        start_date: str | None = None,
        freq: str = "1mo",
        seed: int | None = None,
    ) -> pl.DataFrame:
        r"""Simulate *n_periods* forward paths and return summary statistics.

        Uses **exact simulation** of the OU / Vasicek conditional
        distribution — no Euler-Maruyama time-step bias:

        .. math::

            r_{t+\Delta t} \mid r_t
            \sim \mathcal{N}\!\left(
                \mu(t),\; v(t)
            \right)

        where:

        .. math::

            \mu(t) = \theta + (r_0 - \theta)\, e^{-\kappa t},
            \quad
            v(t) = \frac{\sigma^2}{2\kappa}(1 - e^{-2\kappa t})

        Parameters
        ----------
        n_periods : int
            Number of forward periods (must be >= 1).
        start_date : str or None, optional
            ISO-8601 start date (default ``"2025-01-01"``).
        freq : str, optional
            Polars duration string for the step (default ``"1mo"``).
        seed : int or None, optional
            Random seed for reproducibility.

        Returns
        -------
        pl.DataFrame
            DataFrame with columns ``"Date"``, ``"Mean"``, ``"Median"``,
            ``"Std"``, ``"P5"``, ``"P25"``, ``"P75"``, ``"P95"``,
            ``"Min"``, ``"Max"``.

        Raises
        ------
        Exception_Calculation
            If the model has not been fitted yet.
        Exception_Validation_Input
            If *n_periods* is not a positive integer or *freq* is
            unsupported.

        Examples
        --------
        >>> model = Interest_Rate_Model_Standard(kappa=0.3, theta=0.04, sigma=0.015)
        >>> import polars as pl
        >>> hist = pl.DataFrame(
        ...     {
        ...         "Date": ["2020-01-01", "2021-01-01", "2022-01-01", "2023-01-01", "2024-01-01"],
        ...         "short_rate": [0.025, 0.030, 0.050, 0.053, 0.045],
        ...     }
        ... )
        >>> model.fit(hist)  # doctest: +SKIP
        >>> df = model.predict(12, start_date="2025-01-01", seed=42)  # doctest: +SKIP
        >>> "Mean" in df.columns
        True
        """
        self._check_is_fitted()
        self._validate_n_periods(n_periods)

        if start_date is None:
            start_date = "2025-01-01"

        dt = _freq_to_dt_years(freq)

        dates = _make_date_range(start_date, n_periods, freq)

        rng = np.random.default_rng(seed)

        # Exact OU simulation — shape: (n_periods, n_simulations)
        paths = _simulate_ou_exact(
            kappa=self.m_kappa,
            theta=self.m_theta,
            sigma=self.m_sigma,
            r0=self.m_current_rate,
            n_steps=n_periods,
            n_paths=self.m_n_simulations,
            dt=dt,
            rng=rng,
        )

        logger.info(
            "Interest_Rate_Model_Standard.predict: n_periods=%d, n_sims=%d, freq=%s",
            n_periods,
            self.m_n_simulations,
            freq,
        )

        mean_v = np.mean(paths, axis=1)
        median_v = np.median(paths, axis=1)
        std_v = np.std(paths, axis=1, ddof=1)
        p5 = np.percentile(paths, 5, axis=1)
        p25 = np.percentile(paths, 25, axis=1)
        p75 = np.percentile(paths, 75, axis=1)
        p95 = np.percentile(paths, 95, axis=1)
        min_v = np.min(paths, axis=1)
        max_v = np.max(paths, axis=1)

        return pl.DataFrame(
            {
                "Date": dates,
                "Mean": mean_v.tolist(),
                "Median": median_v.tolist(),
                "Std": std_v.tolist(),
                "P5": p5.tolist(),
                "P25": p25.tolist(),
                "P75": p75.tolist(),
                "P95": p95.tolist(),
                "Min": min_v.tolist(),
                "Max": max_v.tolist(),
            },
        )

    # ------------------------------------------------------------------
    # Scalar rate accessor
    # ------------------------------------------------------------------

    def get_annual_rate(self) -> float:
        r"""Return the long-run mean short rate :math:`\theta`.

        For the Vasicek model the representative scalar rate is the
        stationary mean :math:`\theta`.

        Returns
        -------
        float
            Long-run mean annual short rate in decimal form.

        Raises
        ------
        Exception_Calculation
            If the model has not been fitted yet.
        """
        self._check_is_fitted()
        return self.m_theta

    # ------------------------------------------------------------------
    # Analytical helpers
    # ------------------------------------------------------------------

    def get_analytical_mean(
        self,
        t_years: float,
        r0: float | None = None,
    ) -> float:
        r"""Compute the analytical conditional mean of :math:`r_t`.

        .. math::

            E[r_t \mid r_0] = \theta + (r_0 - \theta)\, e^{-\kappa t}

        Parameters
        ----------
        t_years : float
            Time horizon in years (> 0).
        r0 : float or None, optional
            Starting short rate.  If ``None``, uses :attr:`m_current_rate`.

        Returns
        -------
        float
            Expected short rate at time *t_years*.

        Raises
        ------
        Exception_Calculation
            If the model has not been fitted.
        Exception_Validation_Input
            If *t_years* is not a positive finite float.
        """
        self._check_is_fitted()

        if not isinstance(t_years, float | int) or not np.isfinite(t_years) or t_years <= 0:
            raise Exception_Validation_Input(
                "t_years must be a positive finite number",
                field_name="t_years",
                expected_type=float,
                actual_value=t_years,
            )

        r_start = self.m_current_rate if r0 is None else float(r0)
        return self.m_theta + (r_start - self.m_theta) * np.exp(-self.m_kappa * t_years)

    def get_analytical_variance(self, t_years: float) -> float:
        r"""Compute the analytical conditional variance of :math:`r_t`.

        .. math::

            \mathrm{Var}[r_t \mid r_0]
            = \frac{\sigma^2}{2\kappa}(1 - e^{-2\kappa t})

        Parameters
        ----------
        t_years : float
            Time horizon in years (> 0).

        Returns
        -------
        float
            Conditional variance of the short rate at time *t_years*.

        Raises
        ------
        Exception_Calculation
            If the model has not been fitted.
        Exception_Validation_Input
            If *t_years* is not a positive finite float.
        """
        self._check_is_fitted()

        if not isinstance(t_years, float | int) or not np.isfinite(t_years) or t_years <= 0:
            raise Exception_Validation_Input(
                "t_years must be a positive finite number",
                field_name="t_years",
                expected_type=float,
                actual_value=t_years,
            )

        return (self.m_sigma**2 / (2.0 * self.m_kappa)) * (
            1.0 - np.exp(-2.0 * self.m_kappa * t_years)
        )

    # ------------------------------------------------------------------
    # Dunder overrides
    # ------------------------------------------------------------------

    def __repr__(self) -> str:
        return (
            f"Interest_Rate_Model_Standard("
            f"name='{self.m_name_model}', "
            f"kappa={self.m_kappa:.4f}, "
            f"theta={self.m_theta:.4f}, "
            f"sigma={self.m_sigma:.4f}, "
            f"status={self.m_status.value})"
        )


# ======================================================================
# Private helpers
# ======================================================================


def _validate_positive_float(value: float, name: str) -> None:
    """Raise if *value* is not a positive finite float.

    Parameters
    ----------
    value : float
        Value to check.
    name : str
        Parameter name for the error message.

    Raises
    ------
    Exception_Validation_Input
        If *value* is not a positive finite number.
    """
    if not isinstance(value, float | int) or not np.isfinite(value) or value <= 0:
        raise Exception_Validation_Input(
            f"{name} must be a positive finite number, got {value!r}",
            field_name=name,
            expected_type=float,
            actual_value=value,
        )


def _freq_to_dt_years(freq: str) -> float:
    """Convert a Polars frequency string to a fraction of a year.

    Parameters
    ----------
    freq : str
        Polars duration string (``"1d"``, ``"1mo"``, ``"1y"``).

    Returns
    -------
    float
        Equivalent fraction of a year.

    Raises
    ------
    Exception_Validation_Input
        If *freq* is not one of the supported values.
    """
    mapping: dict[str, float] = {
        "1d": 1.0 / 365.25,
        "1mo": 1.0 / 12.0,
        "1y": 1.0,
    }
    if freq not in mapping:
        raise Exception_Validation_Input(
            f"freq must be one of {sorted(mapping.keys())}, got '{freq}'",
            field_name="freq",
            expected_type=str,
            actual_value=freq,
        )
    return mapping[freq]


def _simulate_ou_exact(
    kappa: float,
    theta: float,
    sigma: float,
    r0: float,
    n_steps: int,
    n_paths: int,
    dt: float,
    rng: np.random.Generator,
) -> np.ndarray:
    r"""Exact simulation of the Vasicek (Ornstein-Uhlenbeck) process.

    Uses the analytical transition distribution:

    .. math::

        r_{t+\Delta t} \mid r_t
        \sim \mathcal{N}\!\left(
            \theta + (r_t - \theta)e^{-\kappa\Delta t},\;
            \frac{\sigma^2}{2\kappa}(1 - e^{-2\kappa\Delta t})
        \right)

    Parameters
    ----------
    kappa : float
        Mean-reversion speed.
    theta : float
        Long-run mean short rate.
    sigma : float
        Short-rate volatility.
    r0 : float
        Starting short rate.
    n_steps : int
        Number of time steps.
    n_paths : int
        Number of Monte Carlo paths.
    dt : float
        Time increment in years.
    rng : np.random.Generator
        NumPy random generator (for reproducibility).

    Returns
    -------
    np.ndarray
        Shape ``(n_steps, n_paths)`` array of simulated short rates.
    """
    e_kdt = np.exp(-kappa * dt)
    cond_var = (sigma**2 / (2.0 * kappa)) * (1.0 - np.exp(-2.0 * kappa * dt))
    cond_std = np.sqrt(max(cond_var, 0.0))

    paths = np.empty((n_steps, n_paths), dtype=np.float64)
    current = np.full(n_paths, r0, dtype=np.float64)

    for t in range(n_steps):
        cond_mean = theta + (current - theta) * e_kdt
        noise = rng.standard_normal(n_paths)
        current = cond_mean + cond_std * noise
        paths[t] = current

    return paths
