# pyright: reportPossiblyUnbound=false
"""Regression tests for azapy portfolio optimization methods.

These tests verify that optimization results from the azapy package wrappers
do not change unexpectedly across code changes, package upgrades, or refactors.

Test Strategy
-------------
Each test:
1. Loads a pre-computed baseline Parquet file (generated by generate_baselines.py).
2. Runs the same optimization with the identical fixed-seed input data.
3. Compares every asset weight against the baseline within the stated tolerance.

Tolerances
----------
* **Deterministic methods** (mean-variance MinRisk, inverse volatility, MAD, etc.):
  ``abs=1e-6``  — results must be identical within floating-point noise.
* **Solver-sensitive methods** (CVaR, EVaR, Kelly): ``abs=1e-5`` — solvers may
  exhibit minor numerical variation across platforms and versions.

Baseline regeneration
---------------------
If a test fails because of an *intentional* algorithmic change:

    python tests/regression_data/portfolio_optimization/generate_baselines.py

Then commit both the code changes and the updated Parquet files together.

Coverage
--------
Functions tested:
    - ``calc_azapy_mean_variance``  (MinRisk, Sharpe)
    - ``calc_azapy_cvar``           (MinRisk, Sharpe at alpha=0.975)
    - ``calc_azapy_mad``            (MinRisk, Sharpe)
    - ``calc_azapy_inverse_volatility``
    - ``calc_azapy_kelly``          (ExpCone)
    - ``calc_azapy_evar``           (MinRisk, Sharpe at alpha=0.975)
"""

from __future__ import annotations

import logging
import typing

from typing import TYPE_CHECKING, Any

import numpy as np
import polars as pl
import pytest


if TYPE_CHECKING:
    from pathlib import Path

from tests.tests_regression.models.portfolio_optimization.conftest import (
    ASSETS,
    FIXED_DATE,
    load_baseline,
)


logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Attempt azapy import — skip all tests if unavailable
# ---------------------------------------------------------------------------
_AZAPY_REASON: str = ""

try:
    from src.models.portfolio_optimization.pkg_azapy import (
        calc_azapy_cvar,
        calc_azapy_evar,
        calc_azapy_inverse_volatility,
        calc_azapy_kelly,
        calc_azapy_mad,
        calc_azapy_mean_variance,
    )

    _AZAPY_AVAILABLE = True
except ImportError as _imp_err:
    _AZAPY_AVAILABLE = False
    _AZAPY_REASON = f"azapy package not available: {_imp_err}"

_skip_if_no_azapy = pytest.mark.skipif(
    not _AZAPY_AVAILABLE,
    reason=_AZAPY_REASON if not _AZAPY_AVAILABLE else "",
)


# ---------------------------------------------------------------------------
# Tolerance constants
# ---------------------------------------------------------------------------
_TOL_DETERMINISTIC: float = 1e-6
_TOL_SOLVER: float = 1e-5
_TOL_WEIGHT_SUM: float = 1e-5


# ---------------------------------------------------------------------------
# Comparison helpers
# ---------------------------------------------------------------------------


def _assert_weights_match_baseline(
    portfolio: object,
    baseline_name: str,
    *,
    tolerance: float = _TOL_DETERMINISTIC,
) -> None:
    """Compare portfolio weights against the stored Parquet baseline.

    Parameters
    ----------
    portfolio:
        Result returned by an azapy optimization function (``portfolio_QWIM``).
    baseline_name:
        Key used to look up the Parquet file (without ``.parquet`` extension).
    tolerance:
        Absolute tolerance for per-asset weight comparison.

    Raises
    ------
    AssertionError
        If any weight deviates from the baseline beyond ``tolerance``.
    FileNotFoundError
        If the baseline Parquet file does not yet exist.
    """
    baseline_df: pl.DataFrame = load_baseline(baseline_name)
    current_weights_df: pl.DataFrame = portfolio.get_portfolio_weights()  # type: ignore[union-attr]

    baseline_asset_cols = [col for col in baseline_df.columns if col != "Date"]
    current_asset_cols = [col for col in current_weights_df.columns if col != "Date"]

    assert set(baseline_asset_cols) == set(current_asset_cols), (
        f"Asset columns differ!\n"
        f"  Baseline: {baseline_asset_cols}\n"
        f"  Current:  {current_asset_cols}"
    )

    mismatches: list[str] = []
    for asset in baseline_asset_cols:
        baseline_w = float(baseline_df[asset][0])
        current_w = float(current_weights_df[asset][0])
        diff = abs(current_w - baseline_w)
        if diff > tolerance:
            mismatches.append(
                f"  {asset}: baseline={baseline_w:.8f}  current={current_w:.8f}  "
                f"diff={diff:.2e}  tol={tolerance:.2e}",
            )

    assert not mismatches, (
        f"Regression failure for '{baseline_name}' "
        f"(tolerance={tolerance:.2e}):\n" + "\n".join(mismatches)
    )

    weight_sum = sum(float(current_weights_df[col][0]) for col in current_asset_cols)
    assert abs(weight_sum - 1.0) < _TOL_WEIGHT_SUM, (
        f"Weights do not sum to 1.0 (sum={weight_sum:.8f})"
    )


def _assert_portfolio_properties(
    portfolio: object,
    *,
    expected_num_assets: int = 5,
) -> None:
    """Validate common structural properties of a portfolio result.

    Parameters
    ----------
    portfolio:
        Portfolio object returned by an optimization function.
    expected_num_assets:
        Expected number of asset columns.
    """
    weights_df: pl.DataFrame = portfolio.get_portfolio_weights()  # type: ignore[union-attr]
    asset_cols = [col for col in weights_df.columns if col != "Date"]

    # Correct number of assets
    assert len(asset_cols) == expected_num_assets, (
        f"Expected {expected_num_assets} assets, got {len(asset_cols)}: {asset_cols}"
    )

    # Single row of weights
    assert len(weights_df) == 1, f"Expected 1 row of weights, got {len(weights_df)}"

    # Weights are finite
    for col in asset_cols:
        weight_val = float(weights_df[col][0])
        assert np.isfinite(weight_val), f"Weight for {col} is not finite: {weight_val}"

    # Weights sum to 1
    weight_sum = sum(float(weights_df[col][0]) for col in asset_cols)
    assert abs(weight_sum - 1.0) < _TOL_WEIGHT_SUM, f"Weights sum to {weight_sum:.8f}, expected 1.0"


# =============================================================================
# Regression tests — azapy Mean-Variance
# =============================================================================


@pytest.mark.regression()
@_skip_if_no_azapy
class Class_Test_Regression_Azapy_Mean_Variance:
    """Regression tests for calc_azapy_mean_variance."""

    def Test_Regression_MV_Min_Risk_Weights(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """Mean-variance MinRisk portfolio weights must match baseline."""
        portfolio = calc_azapy_mean_variance(
            returns_data=canonical_returns_data,
            rtype="MinRisk",
            portfolio_name="regression_azapy_mv_min_risk",
            optimization_date=FIXED_DATE,
        )
        _assert_weights_match_baseline(
            portfolio,
            "azapy_mean_variance_min_risk",
            tolerance=_TOL_DETERMINISTIC,
        )

    def Test_Regression_MV_Sharpe_Weights(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """Mean-variance Sharpe (tangency) portfolio weights must match baseline."""
        portfolio = calc_azapy_mean_variance(
            returns_data=canonical_returns_data,
            rtype="Sharpe",
            portfolio_name="regression_azapy_mv_sharpe",
            optimization_date=FIXED_DATE,
        )
        _assert_weights_match_baseline(
            portfolio,
            "azapy_mean_variance_sharpe",
            tolerance=_TOL_DETERMINISTIC,
        )

    def Test_Regression_MV_Min_Risk_Properties(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """Mean-variance MinRisk portfolio must have valid structural properties."""
        portfolio = calc_azapy_mean_variance(
            returns_data=canonical_returns_data,
            rtype="MinRisk",
            portfolio_name="regression_azapy_mv_props",
            optimization_date=FIXED_DATE,
        )
        _assert_portfolio_properties(portfolio, expected_num_assets=len(ASSETS))

    def Test_Regression_MV_Min_Risk_Non_Negative(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """Mean-variance MinRisk weights must all be non-negative (long-only)."""
        portfolio = calc_azapy_mean_variance(
            returns_data=canonical_returns_data,
            rtype="MinRisk",
            portfolio_name="regression_azapy_mv_nonneg",
            optimization_date=FIXED_DATE,
        )
        weights_df = portfolio.get_portfolio_weights()
        asset_cols = [col for col in weights_df.columns if col != "Date"]
        for asset in asset_cols:
            weight_val = float(weights_df[asset][0])
            assert weight_val >= -1e-8, f"Weight for {asset} is negative: {weight_val:.8f}"


# =============================================================================
# Regression tests — azapy CVaR
# =============================================================================


@pytest.mark.regression()
@_skip_if_no_azapy
class Class_Test_Regression_Azapy_CVaR:
    """Regression tests for calc_azapy_cvar."""

    def Test_Regression_CVaR_Min_Risk_Weights(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """CVaR MinRisk portfolio weights must match baseline."""
        portfolio = calc_azapy_cvar(
            returns_data=canonical_returns_data,
            alpha=0.975,
            rtype="MinRisk",
            portfolio_name="regression_azapy_cvar_min_risk",
            optimization_date=FIXED_DATE,
        )
        _assert_weights_match_baseline(
            portfolio,
            "azapy_cvar_min_risk",
            tolerance=_TOL_SOLVER,
        )

    def Test_Regression_CVaR_Sharpe_Weights(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """CVaR Sharpe portfolio weights must match baseline."""
        portfolio = calc_azapy_cvar(
            returns_data=canonical_returns_data,
            alpha=0.975,
            rtype="Sharpe",
            portfolio_name="regression_azapy_cvar_sharpe",
            optimization_date=FIXED_DATE,
        )
        _assert_weights_match_baseline(
            portfolio,
            "azapy_cvar_sharpe",
            tolerance=_TOL_SOLVER,
        )

    def Test_Regression_CVaR_Min_Risk_Properties(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """CVaR MinRisk portfolio must have valid structural properties."""
        portfolio = calc_azapy_cvar(
            returns_data=canonical_returns_data,
            alpha=0.975,
            rtype="MinRisk",
            portfolio_name="regression_azapy_cvar_props",
            optimization_date=FIXED_DATE,
        )
        _assert_portfolio_properties(portfolio, expected_num_assets=len(ASSETS))

    def Test_Regression_CVaR_Non_Negative(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """CVaR MinRisk weights must all be non-negative (long-only)."""
        portfolio = calc_azapy_cvar(
            returns_data=canonical_returns_data,
            alpha=0.975,
            rtype="MinRisk",
            portfolio_name="regression_azapy_cvar_nonneg",
            optimization_date=FIXED_DATE,
        )
        weights_df = portfolio.get_portfolio_weights()
        asset_cols = [col for col in weights_df.columns if col != "Date"]
        for asset in asset_cols:
            weight_val = float(weights_df[asset][0])
            assert weight_val >= -1e-8, f"CVaR weight for {asset} is negative: {weight_val:.8f}"


# =============================================================================
# Regression tests — azapy MAD
# =============================================================================


@pytest.mark.regression()
@_skip_if_no_azapy
class Class_Test_Regression_Azapy_MAD:
    """Regression tests for calc_azapy_mad."""

    def Test_Regression_MAD_Min_Risk_Weights(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """MAD MinRisk portfolio weights must match baseline."""
        portfolio = calc_azapy_mad(
            returns_data=canonical_returns_data,
            rtype="MinRisk",
            portfolio_name="regression_azapy_mad_min_risk",
            optimization_date=FIXED_DATE,
        )
        _assert_weights_match_baseline(
            portfolio,
            "azapy_mad_min_risk",
            tolerance=_TOL_SOLVER,
        )

    def Test_Regression_MAD_Sharpe_Weights(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """MAD Sharpe portfolio weights must match baseline."""
        portfolio = calc_azapy_mad(
            returns_data=canonical_returns_data,
            rtype="Sharpe",
            portfolio_name="regression_azapy_mad_sharpe",
            optimization_date=FIXED_DATE,
        )
        _assert_weights_match_baseline(
            portfolio,
            "azapy_mad_sharpe",
            tolerance=_TOL_SOLVER,
        )

    def Test_Regression_MAD_Min_Risk_Properties(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """MAD MinRisk portfolio must have valid structural properties."""
        portfolio = calc_azapy_mad(
            returns_data=canonical_returns_data,
            rtype="MinRisk",
            portfolio_name="regression_azapy_mad_props",
            optimization_date=FIXED_DATE,
        )
        _assert_portfolio_properties(portfolio, expected_num_assets=len(ASSETS))


# =============================================================================
# Regression tests — azapy Inverse Volatility
# =============================================================================


@pytest.mark.regression()
@_skip_if_no_azapy
class Class_Test_Regression_Azapy_Inverse_Volatility:
    """Regression tests for calc_azapy_inverse_volatility."""

    def Test_Regression_Inverse_Vol_Weights(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """Inverse volatility portfolio weights must match baseline."""
        portfolio = calc_azapy_inverse_volatility(
            returns_data=canonical_returns_data,
            portfolio_name="regression_azapy_inv_vol",
            optimization_date=FIXED_DATE,
        )
        _assert_weights_match_baseline(
            portfolio,
            "azapy_inverse_volatility",
            tolerance=_TOL_DETERMINISTIC,
        )

    def Test_Regression_Inverse_Vol_Properties(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """Inverse volatility must have valid structural properties."""
        portfolio = calc_azapy_inverse_volatility(
            returns_data=canonical_returns_data,
            portfolio_name="regression_azapy_inv_vol_props",
            optimization_date=FIXED_DATE,
        )
        _assert_portfolio_properties(portfolio, expected_num_assets=len(ASSETS))

    def Test_Regression_Inverse_Vol_Non_Negative(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """Inverse volatility weights must be strictly positive."""
        portfolio = calc_azapy_inverse_volatility(
            returns_data=canonical_returns_data,
            portfolio_name="regression_azapy_inv_vol_pos",
            optimization_date=FIXED_DATE,
        )
        weights_df = portfolio.get_portfolio_weights()
        asset_cols = [col for col in weights_df.columns if col != "Date"]
        for asset in asset_cols:
            weight_val = float(weights_df[asset][0])
            assert weight_val > 0.0, (
                f"Inverse vol weight for {asset} should be positive: {weight_val:.8f}"
            )

    def Test_Regression_Inverse_Vol_Lower_Vol_Gets_Higher_Weight(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """Asset with lower volatility should receive higher weight."""
        portfolio = calc_azapy_inverse_volatility(
            returns_data=canonical_returns_data,
            portfolio_name="regression_azapy_inv_vol_ordering",
            optimization_date=FIXED_DATE,
        )
        weights_df = portfolio.get_portfolio_weights()

        # BND has lowest vol (0.006) and GLD second lowest (0.008)
        # BND should have higher weight than any higher-vol asset
        bnd_weight = float(weights_df["BND"][0])
        vti_weight = float(weights_df["VTI"][0])
        vxus_weight = float(weights_df["VXUS"][0])
        assert bnd_weight > vti_weight, (
            f"BND (lower vol) should have higher weight than VTI: "
            f"BND={bnd_weight:.6f}, VTI={vti_weight:.6f}"
        )
        assert bnd_weight > vxus_weight, (
            f"BND (lower vol) should have higher weight than VXUS: "
            f"BND={bnd_weight:.6f}, VXUS={vxus_weight:.6f}"
        )


# =============================================================================
# Regression tests — azapy Kelly Criterion
# =============================================================================


@pytest.mark.regression()
@_skip_if_no_azapy
class Class_Test_Regression_Azapy_Kelly:
    """Regression tests for calc_azapy_kelly."""

    def Test_Regression_Kelly_ExpCone_Weights(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """Kelly ExpCone portfolio weights must match baseline."""
        portfolio = calc_azapy_kelly(
            returns_data=canonical_returns_data,
            rtype="ExpCone",
            portfolio_name="regression_azapy_kelly",
            optimization_date=FIXED_DATE,
        )
        _assert_weights_match_baseline(
            portfolio,
            "azapy_kelly_exp_cone",
            tolerance=_TOL_SOLVER,
        )

    def Test_Regression_Kelly_ExpCone_Properties(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """Kelly ExpCone portfolio must have valid structural properties."""
        portfolio = calc_azapy_kelly(
            returns_data=canonical_returns_data,
            rtype="ExpCone",
            portfolio_name="regression_azapy_kelly_props",
            optimization_date=FIXED_DATE,
        )
        _assert_portfolio_properties(portfolio, expected_num_assets=len(ASSETS))


# =============================================================================
# Regression tests — azapy EVaR
# =============================================================================


@pytest.mark.regression()
@_skip_if_no_azapy
class Class_Test_Regression_Azapy_EVaR:
    """Regression tests for calc_azapy_evar."""

    def Test_Regression_EVaR_Min_Risk_Weights(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """EVaR MinRisk portfolio weights must match baseline."""
        portfolio = calc_azapy_evar(
            returns_data=canonical_returns_data,
            alpha=0.975,
            rtype="MinRisk",
            portfolio_name="regression_azapy_evar_min_risk",
            optimization_date=FIXED_DATE,
        )
        _assert_weights_match_baseline(
            portfolio,
            "azapy_evar_min_risk",
            tolerance=_TOL_SOLVER,
        )

    def Test_Regression_EVaR_Sharpe_Weights(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """EVaR Sharpe portfolio weights must match baseline."""
        portfolio = calc_azapy_evar(
            returns_data=canonical_returns_data,
            alpha=0.975,
            rtype="Sharpe",
            portfolio_name="regression_azapy_evar_sharpe",
            optimization_date=FIXED_DATE,
        )
        _assert_weights_match_baseline(
            portfolio,
            "azapy_evar_sharpe",
            tolerance=_TOL_SOLVER,
        )

    def Test_Regression_EVaR_Min_Risk_Properties(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """EVaR MinRisk portfolio must have valid structural properties."""
        portfolio = calc_azapy_evar(
            returns_data=canonical_returns_data,
            alpha=0.975,
            rtype="MinRisk",
            portfolio_name="regression_azapy_evar_props",
            optimization_date=FIXED_DATE,
        )
        _assert_portfolio_properties(portfolio, expected_num_assets=len(ASSETS))

    def Test_Regression_EVaR_Non_Negative(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """EVaR MinRisk weights must all be non-negative."""
        portfolio = calc_azapy_evar(
            returns_data=canonical_returns_data,
            alpha=0.975,
            rtype="MinRisk",
            portfolio_name="regression_azapy_evar_nonneg",
            optimization_date=FIXED_DATE,
        )
        weights_df = portfolio.get_portfolio_weights()
        asset_cols = [col for col in weights_df.columns if col != "Date"]
        for asset in asset_cols:
            weight_val = float(weights_df[asset][0])
            assert weight_val >= -1e-8, f"EVaR weight for {asset} is negative: {weight_val:.8f}"


# =============================================================================
# Azapy baseline integrity checks
# =============================================================================


@pytest.mark.regression()
class Class_Test_Regression_Azapy_Baseline_Integrity:
    """Sanity checks that all azapy baseline Parquet files are well-formed."""

    AZAPY_BASELINES: typing.ClassVar[list[str]] = [
        "azapy_mean_variance_min_risk",
        "azapy_mean_variance_sharpe",
        "azapy_cvar_min_risk",
        "azapy_cvar_sharpe",
        "azapy_mad_min_risk",
        "azapy_mad_sharpe",
        "azapy_inverse_volatility",
        "azapy_kelly_exp_cone",
        "azapy_evar_min_risk",
        "azapy_evar_sharpe",
    ]

    @pytest.mark.parametrize("baseline_name", AZAPY_BASELINES)
    def Test_Azapy_Baseline_Parquet_Exists(
        self,
        baselines_dir: Path,
        baseline_name: str,
    ) -> None:
        """Each expected azapy baseline Parquet file must exist."""
        path = baselines_dir / f"{baseline_name}.parquet"
        assert path.exists(), (
            f"Missing azapy baseline: {path}\n"
            "Run: python tests/regression_data/portfolio_optimization/generate_baselines.py"
        )

    @pytest.mark.parametrize("baseline_name", AZAPY_BASELINES)
    def Test_Azapy_Baseline_Is_Readable(
        self,
        baselines_dir: Path,
        baseline_name: str,
    ) -> None:
        """Each azapy baseline Parquet file must be readable as a Polars DataFrame."""
        path = baselines_dir / f"{baseline_name}.parquet"
        if not path.exists():
            pytest.skip(f"Azapy baseline not yet generated: {baseline_name}")
        data_frame = pl.read_parquet(path)
        assert isinstance(data_frame, pl.DataFrame)
        assert len(data_frame) == 1, f"Baseline must have exactly 1 row, got {len(data_frame)}"
        assert "Date" in data_frame.columns

    @pytest.mark.parametrize("baseline_name", AZAPY_BASELINES)
    def Test_Azapy_Baseline_Weights_Sum_To_One(
        self,
        baselines_dir: Path,
        baseline_name: str,
    ) -> None:
        """Azapy baseline weights must sum to 1.0 within tolerance."""
        path = baselines_dir / f"{baseline_name}.parquet"
        if not path.exists():
            pytest.skip(f"Azapy baseline not yet generated: {baseline_name}")
        data_frame = pl.read_parquet(path)
        asset_cols = [col for col in data_frame.columns if col != "Date"]
        weight_sum = sum(float(data_frame[col][0]) for col in asset_cols)
        assert abs(weight_sum - 1.0) < _TOL_WEIGHT_SUM, (
            f"Azapy baseline {baseline_name}: weights sum to {weight_sum:.8f}, expected 1.0"
        )

    @pytest.mark.parametrize("baseline_name", AZAPY_BASELINES)
    def Test_Azapy_Baseline_Weights_Non_Negative(
        self,
        baselines_dir: Path,
        baseline_name: str,
    ) -> None:
        """Azapy baseline weights must all be >= 0 (long-only portfolios)."""
        path = baselines_dir / f"{baseline_name}.parquet"
        if not path.exists():
            pytest.skip(f"Azapy baseline not yet generated: {baseline_name}")
        data_frame = pl.read_parquet(path)
        asset_cols = [col for col in data_frame.columns if col != "Date"]
        for asset in asset_cols:
            weight_val = float(data_frame[asset][0])
            assert weight_val >= -1e-8, (
                f"Azapy baseline {baseline_name}: {asset} weight = {weight_val:.8f} is negative"
            )

    @pytest.mark.parametrize("baseline_name", AZAPY_BASELINES)
    def Test_Azapy_Baseline_Has_Expected_Assets(
        self,
        baselines_dir: Path,
        baseline_name: str,
    ) -> None:
        """Azapy baselines must contain the canonical asset set."""
        path = baselines_dir / f"{baseline_name}.parquet"
        if not path.exists():
            pytest.skip(f"Azapy baseline not yet generated: {baseline_name}")
        data_frame = pl.read_parquet(path)
        asset_cols = sorted(col for col in data_frame.columns if col != "Date")
        expected_assets = sorted(ASSETS)
        assert asset_cols == expected_assets, (
            f"Azapy baseline {baseline_name}: expected assets {expected_assets}, got {asset_cols}"
        )


# =============================================================================
# Cross-method consistency tests
# =============================================================================


@pytest.mark.regression()
@_skip_if_no_azapy
class Class_Test_Regression_Azapy_Cross_Method_Consistency:
    """Verify logical consistency across different azapy optimization methods."""

    def Test_Regression_Inverse_Vol_Matches_Skfolio(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """Azapy inverse-vol and skfolio inverse-vol should produce similar weights.

        Both methods compute 1/sigma_i weights — difference should be small.
        Minor deviations are expected due to different variance estimators.
        """
        azapy_portfolio = calc_azapy_inverse_volatility(
            returns_data=canonical_returns_data,
            portfolio_name="cross_azapy_inv_vol",
            optimization_date=FIXED_DATE,
        )
        azapy_weights = azapy_portfolio.get_portfolio_weights()

        skfolio_baseline = load_baseline("skfolio_basic_inverse_volatility")

        asset_cols = [col for col in azapy_weights.columns if col != "Date"]
        for asset in asset_cols:
            azapy_w = float(azapy_weights[asset][0])
            skfolio_w = float(skfolio_baseline[asset][0])
            diff = abs(azapy_w - skfolio_w)
            # Wider tolerance: different estimators may differ by ~1-5%
            assert diff < 0.10, (
                f"Azapy vs skfolio inverse-vol for {asset}: "
                f"azapy={azapy_w:.6f}, skfolio={skfolio_w:.6f}, diff={diff:.4f}"
            )

    def Test_Regression_Min_Risk_Methods_Differ(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """Different MinRisk methods (MV, CVaR, MAD) should produce different weights.

        While all minimize risk, different risk measures lead to different allocations.
        """
        mv_portfolio = calc_azapy_mean_variance(
            returns_data=canonical_returns_data,
            rtype="MinRisk",
            portfolio_name="cross_mv_min_risk",
            optimization_date=FIXED_DATE,
        )
        cvar_portfolio = calc_azapy_cvar(
            returns_data=canonical_returns_data,
            alpha=0.975,
            rtype="MinRisk",
            portfolio_name="cross_cvar_min_risk",
            optimization_date=FIXED_DATE,
        )

        mv_weights = mv_portfolio.get_portfolio_weights()
        cvar_weights = cvar_portfolio.get_portfolio_weights()

        asset_cols = [col for col in mv_weights.columns if col != "Date"]
        total_diff = sum(
            abs(float(mv_weights[col][0]) - float(cvar_weights[col][0])) for col in asset_cols
        )
        # MV and CVaR usually produce different allocations
        assert total_diff > 1e-6, (
            f"MV and CVaR MinRisk should differ but total weight diff is {total_diff:.8f}"
        )

    def Test_Regression_All_Methods_Valid_Portfolios(
        self,
        canonical_returns_data: pl.DataFrame,
    ) -> None:
        """All azapy methods must produce valid portfolios (weights sum to 1, non-negative)."""
        methods_and_kwargs: list[tuple[str, Any, dict[str, Any]]] = [
            ("MV_MinRisk", calc_azapy_mean_variance, {"rtype": "MinRisk"}),
            ("CVaR_MinRisk", calc_azapy_cvar, {"alpha": 0.975, "rtype": "MinRisk"}),
            ("MAD_MinRisk", calc_azapy_mad, {"rtype": "MinRisk"}),
            ("InvVol", calc_azapy_inverse_volatility, {}),
            ("Kelly", calc_azapy_kelly, {"rtype": "ExpCone"}),
            ("EVaR_MinRisk", calc_azapy_evar, {"alpha": 0.975, "rtype": "MinRisk"}),
        ]

        for method_label, func, kwargs in methods_and_kwargs:
            portfolio = func(
                returns_data=canonical_returns_data,
                portfolio_name=f"cross_all_{method_label}",
                optimization_date=FIXED_DATE,
                **kwargs,
            )
            weights_df = portfolio.get_portfolio_weights()
            asset_cols = [col for col in weights_df.columns if col != "Date"]

            weight_sum = sum(float(weights_df[col][0]) for col in asset_cols)
            assert abs(weight_sum - 1.0) < _TOL_WEIGHT_SUM, (
                f"{method_label}: weights sum to {weight_sum:.8f}"
            )

            for asset in asset_cols:
                weight_val = float(weights_df[asset][0])
                assert weight_val >= -1e-8, (
                    f"{method_label}: {asset} weight is negative ({weight_val:.8f})"
                )
