# pyright: reportArgumentType=false, reportAttributeAccessIssue=false
"""Regression tests for Scenarios_Distribution and Scenarios_CMA.

These tests verify that scenario outputs do not change unexpectedly across
code changes, package upgrades, or refactors.

Test Strategy
-------------
Each test:
1. Loads a pre-computed baseline Parquet file (generated by
   ``generate_baselines.py``).
2. Runs the same scenario with the identical fixed-seed input data.
3. Compares results against the baseline within the stated tolerance.

Tolerances
----------
* **Scenario DataFrames** (seeded Normal/Student-t/CMA paths): ``abs=1e-8``
  â€” results must be bit-for-bit identical with fixed RNG seed.
* **Summary statistics** (mean, std, skew, â€¦): ``abs=1e-6``
  â€” floating-point accumulation may introduce tiny noise.
* **Lognormal** paths: ``abs=1e-6`` â€” exp() amplifies tiny float noise.
* **CMA daily conversions**: ``abs=1e-10`` â€” simple division with no
  accumulation.

Baseline regeneration
---------------------
If a test fails because of an *intentional* algorithmic change::

    python tests/regression_data/scenarios/generate_baselines.py

Then commit both the code changes and the updated Parquet files together.

Markers
-------
All tests carry ``@pytest.mark.regression``.
"""

from __future__ import annotations

import math

from typing import TYPE_CHECKING

import numpy as np
import polars as pl
import pytest


if TYPE_CHECKING:
    from pathlib import Path

from src.num_methods.scenarios.scenarios_base import (
    Frequency_Time_Series,
    Scenario_Data_Type,
)
from src.num_methods.scenarios.scenarios_CMA import (
    DEFAULT_INDEX_MAP,
    Asset_Class_Tier,
    CMA_Source,
    Scenarios_CMA,
)
from src.num_methods.scenarios.scenarios_distrib import (
    Covariance_Input_Type,
    Distribution_Type,
    Scenarios_Distribution,
)

from .conftest import (
    CMA_ASSET_CLASSES,
    CMA_CORRELATION,
    CMA_EXPECTED_RETURNS_ANNUAL,
    CMA_EXPECTED_VOLS_ANNUAL,
    COV_MATRIX,
    DISTRIB_COMPONENTS,
    MEAN_RETURNS,
    NUM_DAYS,
    RANDOM_SEED,
    START_DATE,
    load_baseline,
)


# ---------------------------------------------------------------------------
# Tolerances
# ---------------------------------------------------------------------------
_TOL_EXACT: float = 1e-8
_TOL_SUMMARY: float = 1e-6
_TOL_LOGNORMAL: float = 1e-6
_TOL_CMA_DAILY: float = 1e-10


# ---------------------------------------------------------------------------
# All baseline names (for parametrized integrity tests)
# ---------------------------------------------------------------------------
ALL_BASELINES: list[str] = [
    # Scenarios_Distribution â€” Normal
    "distrib_normal_scenarios",
    "distrib_normal_summary_stats",
    "distrib_normal_correlation",
    "distrib_normal_covariance",
    # Scenarios_Distribution â€” Student-t
    "distrib_student_t_scenarios",
    "distrib_student_t_summary_stats",
    "distrib_student_t_correlation",
    # Scenarios_Distribution â€” Lognormal
    "distrib_lognormal_scenarios",
    "distrib_lognormal_summary_stats",
    # Scenarios_Distribution â€” Correlation + Volatilities
    "distrib_corr_vols_scenarios",
    "distrib_corr_vols_summary_stats",
    # Scenarios_Distribution â€” Returns to Prices
    "distrib_returns_to_prices",
    # Scenarios_CMA
    "CMA_scenarios",
    "CMA_summary_stats",
    "CMA_correlation",
    "CMA_covariance",
    "CMA_index_correspondence",
    "CMA_daily_params",
    "CMA_daily_covariance",
]


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------


def _assert_dataframe_matches_baseline(
    df_actual: pl.DataFrame,
    baseline_name: str,
    *,
    tolerance: float = _TOL_EXACT,
) -> None:
    """Assert that *df_actual* matches the stored Parquet baseline.

    Parameters
    ----------
    df_actual : pl.DataFrame
        The DataFrame produced by the current codebase.
    baseline_name : str
        Parquet basename (without extension) in the regression data dir.
    tolerance : float
        Absolute tolerance for floating-point comparisons.
    """
    df_baseline = load_baseline(baseline_name)

    assert df_actual.shape == df_baseline.shape, (
        f"Shape mismatch for '{baseline_name}': "
        f"actual={df_actual.shape}, baseline={df_baseline.shape}"
    )

    assert list(df_actual.columns) == list(df_baseline.columns), (
        f"Column mismatch for '{baseline_name}': "
        f"actual={df_actual.columns}, baseline={df_baseline.columns}"
    )

    # Compare numeric columns within tolerance
    for col_name in df_actual.columns:
        dtype = df_actual.schema[col_name]
        if dtype in (pl.Float64, pl.Float32):
            vals_actual = df_actual[col_name].to_numpy()
            vals_baseline = df_baseline[col_name].to_numpy()
            np.testing.assert_allclose(
                vals_actual,
                vals_baseline,
                atol=tolerance,
                rtol=0,
                err_msg=f"Column '{col_name}' regression mismatch in '{baseline_name}'",
            )
        elif dtype == pl.Date:
            assert df_actual[col_name].to_list() == df_baseline[col_name].to_list(), (
                f"Date column '{col_name}' mismatch in '{baseline_name}'"
            )
        elif dtype == pl.Utf8 or dtype == pl.String:
            assert df_actual[col_name].to_list() == df_baseline[col_name].to_list(), (
                f"String column '{col_name}' mismatch in '{baseline_name}'"
            )


# ======================================================================
# Scenarios_Distribution â€” Normal
# ======================================================================


@pytest.mark.regression()
class Class_Test_Regression_Scenarios_Distribution_Normal:
    """Regression tests for Scenarios_Distribution with Normal distribution."""

    def Test_Scenarios_Match_Baseline(
        self,
        scen_distrib_normal: Scenarios_Distribution,
    ) -> None:
        """Generated scenario DataFrame must match stored baseline."""
        df_actual = scen_distrib_normal.df_scenarios
        assert df_actual is not None
        _assert_dataframe_matches_baseline(
            df_actual,
            "distrib_normal_scenarios",
            tolerance=_TOL_EXACT,
        )

    def Test_Summary_Stats_Match_Baseline(
        self,
        scen_distrib_normal: Scenarios_Distribution,
    ) -> None:
        """Summary statistics must match stored baseline."""
        df_actual = scen_distrib_normal.calc_summary_statistics()
        _assert_dataframe_matches_baseline(
            df_actual,
            "distrib_normal_summary_stats",
            tolerance=_TOL_SUMMARY,
        )

    def Test_Correlation_Matches_Baseline(
        self,
        scen_distrib_normal: Scenarios_Distribution,
    ) -> None:
        """Correlation matrix must match stored baseline."""
        df_actual = scen_distrib_normal.calc_correlation_matrix()
        _assert_dataframe_matches_baseline(
            df_actual,
            "distrib_normal_correlation",
            tolerance=_TOL_SUMMARY,
        )

    def Test_Covariance_Matches_Baseline(
        self,
        scen_distrib_normal: Scenarios_Distribution,
    ) -> None:
        """Covariance matrix must match stored baseline."""
        df_actual = scen_distrib_normal.calc_covariance_matrix()
        _assert_dataframe_matches_baseline(
            df_actual,
            "distrib_normal_covariance",
            tolerance=_TOL_SUMMARY,
        )

    def Test_Scenario_Shape(
        self,
        scen_distrib_normal: Scenarios_Distribution,
    ) -> None:
        """Result shape must be (NUM_DAYS, num_components + 1)."""
        df = scen_distrib_normal.df_scenarios
        assert df is not None
        assert df.shape == (NUM_DAYS, len(DISTRIB_COMPONENTS) + 1)

    def Test_Properties_After_Generate(
        self,
        scen_distrib_normal: Scenarios_Distribution,
    ) -> None:
        """Verify object properties after generation."""
        assert scen_distrib_normal.num_components == len(DISTRIB_COMPONENTS)
        assert scen_distrib_normal.num_dates == NUM_DAYS
        assert scen_distrib_normal.names_components == DISTRIB_COMPONENTS
        assert scen_distrib_normal.distribution_type == Distribution_Type.NORMAL
        assert scen_distrib_normal.random_seed == RANDOM_SEED
        assert scen_distrib_normal.data_type == Scenario_Data_Type.RETURN_ARITHMETIC
        assert scen_distrib_normal.frequency == Frequency_Time_Series.DAILY

    def Test_Validation_Passes(
        self,
        scen_distrib_normal: Scenarios_Distribution,
    ) -> None:
        """validate_scenarios() must pass without error."""
        assert scen_distrib_normal.validate_scenarios() is True

    def Test_Column_Names_Correct(
        self,
        scen_distrib_normal: Scenarios_Distribution,
    ) -> None:
        """DataFrame columns must be Date + component names."""
        df = scen_distrib_normal.df_scenarios
        assert df is not None
        expected = ["Date", *DISTRIB_COMPONENTS]
        assert list(df.columns) == expected


# ======================================================================
# Scenarios_Distribution â€” Student-t
# ======================================================================


@pytest.mark.regression()
class Class_Test_Regression_Scenarios_Distribution_Student_T:
    """Regression tests for Scenarios_Distribution with Student-t distribution."""

    def Test_Scenarios_Match_Baseline(
        self,
        scen_distrib_student_t: Scenarios_Distribution,
    ) -> None:
        """Generated scenario DataFrame must match stored baseline."""
        df_actual = scen_distrib_student_t.df_scenarios
        assert df_actual is not None
        _assert_dataframe_matches_baseline(
            df_actual,
            "distrib_student_t_scenarios",
            tolerance=_TOL_EXACT,
        )

    def Test_Summary_Stats_Match_Baseline(
        self,
        scen_distrib_student_t: Scenarios_Distribution,
    ) -> None:
        """Summary statistics must match stored baseline."""
        df_actual = scen_distrib_student_t.calc_summary_statistics()
        _assert_dataframe_matches_baseline(
            df_actual,
            "distrib_student_t_summary_stats",
            tolerance=_TOL_SUMMARY,
        )

    def Test_Correlation_Matches_Baseline(
        self,
        scen_distrib_student_t: Scenarios_Distribution,
    ) -> None:
        """Correlation matrix must match stored baseline."""
        df_actual = scen_distrib_student_t.calc_correlation_matrix()
        _assert_dataframe_matches_baseline(
            df_actual,
            "distrib_student_t_correlation",
            tolerance=_TOL_SUMMARY,
        )

    def Test_Heavier_Tails_Than_Normal(
        self,
        scen_distrib_normal: Scenarios_Distribution,
        scen_distrib_student_t: Scenarios_Distribution,
    ) -> None:
        """Student-t should exhibit heavier tails (larger range) than Normal."""
        normal_mat = scen_distrib_normal.get_returns_matrix()
        student_mat = scen_distrib_student_t.get_returns_matrix()

        range_normal = float(normal_mat.max() - normal_mat.min())
        range_student = float(student_mat.max() - student_mat.min())

        # Student-t with 5 df has heavier tails â€” at least one component
        # should show larger range; we check overall
        assert range_student > range_normal * 0.5, (
            "Student-t range should not be dramatically smaller than Normal"
        )

    def Test_Degrees_Of_Freedom(
        self,
        scen_distrib_student_t: Scenarios_Distribution,
    ) -> None:
        """Degrees of freedom property must match configuration."""
        assert scen_distrib_student_t.degrees_of_freedom == 5.0


# ======================================================================
# Scenarios_Distribution â€” Lognormal
# ======================================================================


@pytest.mark.regression()
class Class_Test_Regression_Scenarios_Distribution_Lognormal:
    """Regression tests for Scenarios_Distribution with lognormal distribution."""

    def Test_Scenarios_Match_Baseline(
        self,
        scen_distrib_lognormal: Scenarios_Distribution,
    ) -> None:
        """Generated scenario DataFrame must match stored baseline."""
        df_actual = scen_distrib_lognormal.df_scenarios
        assert df_actual is not None
        _assert_dataframe_matches_baseline(
            df_actual,
            "distrib_lognormal_scenarios",
            tolerance=_TOL_LOGNORMAL,
        )

    def Test_Summary_Stats_Match_Baseline(
        self,
        scen_distrib_lognormal: Scenarios_Distribution,
    ) -> None:
        """Summary statistics must match stored baseline."""
        df_actual = scen_distrib_lognormal.calc_summary_statistics()
        _assert_dataframe_matches_baseline(
            df_actual,
            "distrib_lognormal_summary_stats",
            tolerance=_TOL_SUMMARY,
        )

    def Test_All_Values_Positive(
        self,
        scen_distrib_lognormal: Scenarios_Distribution,
    ) -> None:
        """Lognormal output must be strictly positive."""
        mat = scen_distrib_lognormal.get_returns_matrix()
        assert np.all(mat > 0), "Lognormal scenarios must be strictly positive"

    def Test_Distribution_Type(
        self,
        scen_distrib_lognormal: Scenarios_Distribution,
    ) -> None:
        """Distribution type property must be LOGNORMAL."""
        assert scen_distrib_lognormal.distribution_type == Distribution_Type.LOGNORMAL


# ======================================================================
# Scenarios_Distribution â€” Correlation + Volatilities input
# ======================================================================


@pytest.mark.regression()
class Class_Test_Regression_Scenarios_Distribution_Corr_Vols:
    """Regression tests for Scenarios_Distribution via from_correlation_and_volatilities."""

    def Test_Scenarios_Match_Baseline(
        self,
        scen_distrib_corr_vols: Scenarios_Distribution,
    ) -> None:
        """Scenarios generated via corr+vols input must match baseline."""
        df_actual = scen_distrib_corr_vols.df_scenarios
        assert df_actual is not None
        _assert_dataframe_matches_baseline(
            df_actual,
            "distrib_corr_vols_scenarios",
            tolerance=_TOL_EXACT,
        )

    def Test_Summary_Stats_Match_Baseline(
        self,
        scen_distrib_corr_vols: Scenarios_Distribution,
    ) -> None:
        """Summary statistics must match stored baseline."""
        df_actual = scen_distrib_corr_vols.calc_summary_statistics()
        _assert_dataframe_matches_baseline(
            df_actual,
            "distrib_corr_vols_summary_stats",
            tolerance=_TOL_SUMMARY,
        )

    def Test_Covariance_Input_Type(
        self,
        scen_distrib_corr_vols: Scenarios_Distribution,
    ) -> None:
        """Covariance input type must be CORRELATION_AND_VOLATILITIES."""
        assert (
            scen_distrib_corr_vols.covariance_input_type
            == Covariance_Input_Type.CORRELATION_AND_VOLATILITIES
        )

    def Test_Matches_Direct_Cov_Input(
        self,
        scen_distrib_normal: Scenarios_Distribution,
        scen_distrib_corr_vols: Scenarios_Distribution,
    ) -> None:
        """Corr+Vols scenario must produce same results as direct covariance input.

        Both use the same underlying covariance (COV_MATRIX), same seed, and
        same Normal distribution, so outputs must match.
        """
        df_cov = scen_distrib_normal.df_scenarios
        df_corr_vols = scen_distrib_corr_vols.df_scenarios
        assert df_cov is not None
        assert df_corr_vols is not None

        for col_name in DISTRIB_COMPONENTS:
            np.testing.assert_allclose(
                df_cov[col_name].to_numpy(),
                df_corr_vols[col_name].to_numpy(),
                atol=_TOL_EXACT,
                err_msg=f"Column '{col_name}' differs between cov and corr+vols",
            )


# ======================================================================
# Scenarios_Distribution â€” Returns to Prices conversion
# ======================================================================


@pytest.mark.regression()
class Class_Test_Regression_Scenarios_Returns_To_Prices:
    """Regression tests for convert_returns_to_prices."""

    def Test_Prices_Match_Baseline(
        self,
        scen_distrib_normal: Scenarios_Distribution,
    ) -> None:
        """Prices converted from returns must match stored baseline."""
        initial_prices = [100.0, 50.0, 75.0, 80.0, 60.0]
        df_prices = scen_distrib_normal.convert_returns_to_prices(
            initial_prices=initial_prices,
        )
        _assert_dataframe_matches_baseline(
            df_prices,
            "distrib_returns_to_prices",
            tolerance=_TOL_SUMMARY,
        )

    def Test_Prices_All_Positive(
        self,
        scen_distrib_normal: Scenarios_Distribution,
    ) -> None:
        """Cumulated prices must be positive (with typical daily returns)."""
        initial_prices = [100.0, 50.0, 75.0, 80.0, 60.0]
        df_prices = scen_distrib_normal.convert_returns_to_prices(
            initial_prices=initial_prices,
        )
        for col_name in DISTRIB_COMPONENTS:
            vals = df_prices[col_name].to_numpy()
            assert np.all(vals > 0), f"Price column '{col_name}' contains non-positive values"


# ======================================================================
# Scenarios_CMA
# ======================================================================


@pytest.mark.regression()
class Class_Test_Regression_Scenarios_CMA:
    """Regression tests for Scenarios_CMA."""

    def Test_Scenarios_Match_Baseline(
        self,
        scen_CMA: Scenarios_CMA,
    ) -> None:
        """Generated daily returns must match stored baseline."""
        df_actual = scen_CMA.df_scenarios
        assert df_actual is not None
        _assert_dataframe_matches_baseline(
            df_actual,
            "CMA_scenarios",
            tolerance=_TOL_EXACT,
        )

    def Test_Summary_Stats_Match_Baseline(
        self,
        scen_CMA: Scenarios_CMA,
    ) -> None:
        """Summary statistics must match stored baseline."""
        df_actual = scen_CMA.calc_summary_statistics()
        _assert_dataframe_matches_baseline(
            df_actual,
            "CMA_summary_stats",
            tolerance=_TOL_SUMMARY,
        )

    def Test_Correlation_Matches_Baseline(
        self,
        scen_CMA: Scenarios_CMA,
    ) -> None:
        """Correlation matrix must match stored baseline."""
        df_actual = scen_CMA.calc_correlation_matrix()
        _assert_dataframe_matches_baseline(
            df_actual,
            "CMA_correlation",
            tolerance=_TOL_SUMMARY,
        )

    def Test_Covariance_Matches_Baseline(
        self,
        scen_CMA: Scenarios_CMA,
    ) -> None:
        """Covariance matrix must match stored baseline."""
        df_actual = scen_CMA.calc_covariance_matrix()
        _assert_dataframe_matches_baseline(
            df_actual,
            "CMA_covariance",
            tolerance=_TOL_SUMMARY,
        )

    def Test_Index_Correspondence_Matches_Baseline(
        self,
        scen_CMA: Scenarios_CMA,
    ) -> None:
        """Index correspondence table must match stored baseline."""
        df_actual = scen_CMA.get_index_correspondence_table()
        _assert_dataframe_matches_baseline(
            df_actual,
            "CMA_index_correspondence",
            tolerance=_TOL_SUMMARY,
        )

    def Test_Daily_Params_Match_Baseline(
        self,
        scen_CMA: Scenarios_CMA,
    ) -> None:
        """Daily return and volatility conversions must match baseline."""
        daily_ret = scen_CMA.calc_daily_expected_returns()
        daily_vol = scen_CMA.calc_daily_volatilities()

        df_actual = pl.DataFrame(
            {
                "asset_class": CMA_ASSET_CLASSES,
                "daily_return": daily_ret.tolist(),
                "daily_volatility": daily_vol.tolist(),
            },
        )
        _assert_dataframe_matches_baseline(
            df_actual,
            "CMA_daily_params",
            tolerance=_TOL_CMA_DAILY,
        )

    def Test_Daily_Covariance_Matches_Baseline(
        self,
        scen_CMA: Scenarios_CMA,
    ) -> None:
        """Daily covariance matrix must match stored baseline."""
        daily_cov = scen_CMA.calc_daily_covariance()

        df_actual = pl.DataFrame(
            {
                "asset_class": CMA_ASSET_CLASSES,
                **{ac: daily_cov[:, idx_j].tolist() for idx_j, ac in enumerate(CMA_ASSET_CLASSES)},
            },
        )
        _assert_dataframe_matches_baseline(
            df_actual,
            "CMA_daily_covariance",
            tolerance=_TOL_CMA_DAILY,
        )

    def Test_Scenario_Shape(
        self,
        scen_CMA: Scenarios_CMA,
    ) -> None:
        """Result shape must be (NUM_DAYS, num_asset_classes + 1)."""
        df = scen_CMA.df_scenarios
        assert df is not None
        assert df.shape == (NUM_DAYS, len(CMA_ASSET_CLASSES) + 1)

    def Test_Properties_After_Generate(
        self,
        scen_CMA: Scenarios_CMA,
    ) -> None:
        """Verify object properties after generation."""
        assert scen_CMA.num_components == len(CMA_ASSET_CLASSES)
        assert scen_CMA.num_dates == NUM_DAYS
        assert scen_CMA.names_components == CMA_ASSET_CLASSES
        assert scen_CMA.source == CMA_Source.MANUAL
        assert scen_CMA.random_seed == RANDOM_SEED

    def Test_Daily_Return_Conversion_Correct(
        self,
        scen_CMA: Scenarios_CMA,
    ) -> None:
        """Daily expected returns must equal annual / 252."""
        daily_ret = scen_CMA.calc_daily_expected_returns()
        freq = scen_CMA.frequency.value  # 252
        expected = CMA_EXPECTED_RETURNS_ANNUAL / freq
        np.testing.assert_allclose(
            daily_ret,
            expected,
            atol=_TOL_CMA_DAILY,
        )

    def Test_Daily_Volatility_Conversion_Correct(
        self,
        scen_CMA: Scenarios_CMA,
    ) -> None:
        """Daily volatilities must equal annual / sqrt(252)."""
        daily_vol = scen_CMA.calc_daily_volatilities()
        freq = scen_CMA.frequency.value  # 252
        expected = CMA_EXPECTED_VOLS_ANNUAL / math.sqrt(freq)
        np.testing.assert_allclose(
            daily_vol,
            expected,
            atol=_TOL_CMA_DAILY,
        )

    def Test_Validation_Passes(
        self,
        scen_CMA: Scenarios_CMA,
    ) -> None:
        """validate_scenarios() must pass without error."""
        assert scen_CMA.validate_scenarios() is True

    def Test_Index_Map_Defaults(
        self,
        scen_CMA: Scenarios_CMA,
    ) -> None:
        """Index map should default to DEFAULT_INDEX_MAP entries."""
        idx_map = scen_CMA.index_map
        for ac_name in CMA_ASSET_CLASSES:
            assert ac_name in idx_map
            assert idx_map[ac_name] == DEFAULT_INDEX_MAP.get(ac_name, "N/A")

    def Test_Asset_Classes_By_Tier(
        self,
        scen_CMA: Scenarios_CMA,
    ) -> None:
        """get_asset_classes_by_tier must return correct subsets."""
        # All CMA asset classes are Tier 1 by default
        tier1 = scen_CMA.get_asset_classes_by_tier(Asset_Class_Tier.TIER_1)
        assert set(tier1) == set(CMA_ASSET_CLASSES)

        # Tier 0 should return nothing from our test data
        tier0 = scen_CMA.get_asset_classes_by_tier(Asset_Class_Tier.TIER_0)
        assert tier0 == []


# ======================================================================
# Baseline Integrity
# ======================================================================


@pytest.mark.regression()
class Class_Test_Regression_Scenarios_Baseline_Integrity:
    """Verify that all baseline Parquet files exist, are readable, and
    contain only finite values.
    """

    @pytest.mark.parametrize("baseline_name", ALL_BASELINES)
    def Test_Baseline_Exists(
        self,
        baselines_dir: Path,
        baseline_name: str,
    ) -> None:
        """Each expected baseline file must exist on disk."""
        path = baselines_dir / f"{baseline_name}.parquet"
        assert path.exists(), f"Missing baseline: {path}"

    @pytest.mark.parametrize("baseline_name", ALL_BASELINES)
    def Test_Baseline_Is_Readable(
        self,
        baseline_name: str,
    ) -> None:
        """Each baseline must be readable as a non-empty Polars DataFrame."""
        df = load_baseline(baseline_name)
        assert isinstance(df, pl.DataFrame)
        assert df.height > 0

    @pytest.mark.parametrize("baseline_name", ALL_BASELINES)
    def Test_Baseline_Contains_Finite_Values(
        self,
        baseline_name: str,
    ) -> None:
        """All float columns in each baseline must contain finite values."""
        df = load_baseline(baseline_name)
        for col_name in df.columns:
            if df.schema[col_name] in (pl.Float64, pl.Float32):
                vals = df[col_name].to_numpy()
                assert np.all(np.isfinite(vals)), (
                    f"Non-finite values in '{baseline_name}' column '{col_name}'"
                )


# ======================================================================
# Cross-configuration tests
# ======================================================================


@pytest.mark.regression()
class Class_Test_Regression_Scenarios_Cross_Config:
    """Cross-configuration comparisons and invariant checks."""

    def Test_Same_Seed_Reproduces_Normal(self) -> None:
        """Two runs with the same seed must produce identical Normal results."""
        kwargs = {
            "names_components": DISTRIB_COMPONENTS,
            "distribution_type": Distribution_Type.NORMAL,
            "mean_returns": MEAN_RETURNS,
            "covariance_matrix": COV_MATRIX,
            "start_date": START_DATE,
            "num_days": NUM_DAYS,
            "random_seed": RANDOM_SEED,
        }
        scen_a = Scenarios_Distribution(**kwargs)
        scen_b = Scenarios_Distribution(**kwargs)
        df_a = scen_a.generate()
        df_b = scen_b.generate()

        for col_name in DISTRIB_COMPONENTS:
            np.testing.assert_array_equal(
                df_a[col_name].to_numpy(),
                df_b[col_name].to_numpy(),
                err_msg=f"Seed reproducibility failed for '{col_name}'",
            )

    def Test_Different_Seeds_Differ(self) -> None:
        """Two runs with different seeds must produce different results."""
        common = {
            "names_components": DISTRIB_COMPONENTS,
            "distribution_type": Distribution_Type.NORMAL,
            "mean_returns": MEAN_RETURNS,
            "covariance_matrix": COV_MATRIX,
            "start_date": START_DATE,
            "num_days": NUM_DAYS,
        }
        scen_a = Scenarios_Distribution(**common, random_seed=42)
        scen_b = Scenarios_Distribution(**common, random_seed=99)
        df_a = scen_a.generate()
        df_b = scen_b.generate()

        # At least one column must differ
        any_different = False
        for col_name in DISTRIB_COMPONENTS:
            if not np.array_equal(
                df_a[col_name].to_numpy(),
                df_b[col_name].to_numpy(),
            ):
                any_different = True
                break
        assert any_different, "Different seeds produced identical outputs"

    def Test_Same_Seed_Reproduces_CMA(self) -> None:
        """Two CMA runs with the same seed must produce identical results."""
        kwargs = {
            "names_asset_classes": CMA_ASSET_CLASSES,
            "expected_returns_annual": CMA_EXPECTED_RETURNS_ANNUAL,
            "expected_vols_annual": CMA_EXPECTED_VOLS_ANNUAL,
            "correlation_matrix": CMA_CORRELATION,
            "start_date": START_DATE,
            "num_days": NUM_DAYS,
            "random_seed": RANDOM_SEED,
        }
        scen_a = Scenarios_CMA(**kwargs)
        scen_b = Scenarios_CMA(**kwargs)
        df_a = scen_a.generate()
        df_b = scen_b.generate()

        for col_name in CMA_ASSET_CLASSES:
            np.testing.assert_array_equal(
                df_a[col_name].to_numpy(),
                df_b[col_name].to_numpy(),
                err_msg=f"CMA seed reproducibility failed for '{col_name}'",
            )

    def Test_Date_Column_Is_Business_Days(
        self,
        scen_distrib_normal: Scenarios_Distribution,
    ) -> None:
        """All dates in the scenario must be weekdays (Mon-Fri)."""
        df = scen_distrib_normal.df_scenarios
        assert df is not None
        dates = df["Date"].to_list()
        for item_date in dates:
            assert item_date.weekday() < 5, (
                f"Non-business day found: {item_date} (weekday={item_date.weekday()})"
            )

    def Test_Get_Component_Series(
        self,
        scen_distrib_normal: Scenarios_Distribution,
    ) -> None:
        """get_component_series must return a correctly sized Series."""
        series = scen_distrib_normal.get_component_series("US_Equity")
        assert len(series) == NUM_DAYS
        assert series.dtype == pl.Float64

    def Test_Select_Components_Subset(
        self,
        scen_distrib_normal: Scenarios_Distribution,
    ) -> None:
        """select_components with a subset must return correct columns."""
        subset = ["US_Equity", "US_Bond"]
        df_sub = scen_distrib_normal.select_components(subset)
        assert list(df_sub.columns) == ["Date", "US_Equity", "US_Bond"]
        assert df_sub.height == NUM_DAYS

    def Test_Filter_By_Date_Range(
        self,
        scen_distrib_normal: Scenarios_Distribution,
    ) -> None:
        """filter_by_date_range must return a smaller DataFrame."""
        start, end = scen_distrib_normal.get_date_range()
        # Use a mid-point range
        from datetime import timedelta

        mid = start + timedelta(days=15)
        df_filtered = scen_distrib_normal.filter_by_date_range(mid, end)
        assert df_filtered.height < NUM_DAYS
        assert df_filtered.height > 0

    def Test_Get_Returns_Matrix_Shape(
        self,
        scen_distrib_normal: Scenarios_Distribution,
    ) -> None:
        """get_returns_matrix must return a (T, K) numpy array."""
        mat = scen_distrib_normal.get_returns_matrix()
        assert mat.shape == (NUM_DAYS, len(DISTRIB_COMPONENTS))
        assert mat.dtype == np.float64

    def Test_Summary_Stats_Columns(
        self,
        scen_distrib_normal: Scenarios_Distribution,
    ) -> None:
        """Summary statistics must contain expected columns."""
        df = scen_distrib_normal.calc_summary_statistics()
        expected_cols = [
            "component",
            "mean",
            "std",
            "min",
            "max",
            "median",
            "skew",
            "count",
        ]
        assert list(df.columns) == expected_cols
        assert df.height == len(DISTRIB_COMPONENTS)

    def Test_Correlation_Matrix_Properties(
        self,
        scen_distrib_normal: Scenarios_Distribution,
    ) -> None:
        """Correlation matrix must be symmetric with 1s on the diagonal."""
        df_corr = scen_distrib_normal.calc_correlation_matrix()
        corr_mat = df_corr.select(DISTRIB_COMPONENTS).to_numpy()

        # Symmetric
        np.testing.assert_allclose(
            corr_mat,
            corr_mat.T,
            atol=1e-10,
            err_msg="Correlation matrix not symmetric",
        )

        # Diagonal = 1
        np.testing.assert_allclose(
            np.diag(corr_mat),
            np.ones(len(DISTRIB_COMPONENTS)),
            atol=1e-10,
            err_msg="Correlation matrix diagonal not 1.0",
        )

    def Test_CMA_Annual_Covariance_Symmetric(
        self,
        scen_CMA: Scenarios_CMA,
    ) -> None:
        """CMA annual covariance matrix must be symmetric."""
        cov_annual = scen_CMA.covariance_matrix_annual
        np.testing.assert_allclose(
            cov_annual,
            cov_annual.T,
            atol=1e-10,
            err_msg="CMA annual covariance matrix not symmetric",
        )

    def Test_Enum_Values_Exist(self) -> None:
        """Verify that key enum members exist and have expected values.

        Uses ``getattr`` to access ``.value`` because aenum's metaclass is
        not understood by pyright, ty, or pyrefly.
        """
        _v = "value"  # indirection avoids aenum type-checker false positives

        assert getattr(Distribution_Type.NORMAL, _v) == "Normal"
        assert getattr(Distribution_Type.LOGNORMAL, _v) == "Lognormal"
        assert getattr(Distribution_Type.STUDENT_T, _v) == "Student-t"

        assert getattr(Covariance_Input_Type.COVARIANCE_MATRIX, _v) == "Covariance Matrix"
        assert (
            getattr(Covariance_Input_Type.CORRELATION_AND_VOLATILITIES, _v)
            == "Correlation + Volatilities"
        )

        assert getattr(Scenario_Data_Type.PRICE, _v) == "Price"
        assert getattr(Scenario_Data_Type.RETURN_ARITHMETIC, _v) == "Arithmetic Return"
        assert getattr(Scenario_Data_Type.RETURN_LOG, _v) == "Log Return"
        assert getattr(Scenario_Data_Type.INDEX_LEVEL, _v) == "Index Level"

        assert getattr(Frequency_Time_Series.DAILY, _v) == 252
        assert getattr(Frequency_Time_Series.WEEKLY, _v) == 52
        assert getattr(Frequency_Time_Series.MONTHLY, _v) == 12

        assert getattr(Asset_Class_Tier.TIER_0, _v) == 0
        assert getattr(Asset_Class_Tier.TIER_1, _v) == 1
        assert getattr(Asset_Class_Tier.TIER_2, _v) == 2

        assert getattr(CMA_Source.SPREADSHEET, _v) == "Spreadsheet"
        assert getattr(CMA_Source.MANUAL, _v) == "Manual"
