"""Regression tests for interest-rate models.

Compares current model outputs against stored Parquet baselines to detect
unintended behavioural changes.  Baselines are generated by
``tests/regression_data/interest_rate/generate_baselines.py``.

Usage
-----
    pytest tests/tests_regression/models/interest_rate/ -v -m regression
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np
import polars as pl
import pytest

from tests.tests_regression.models.interest_rate.conftest import (  # pyright: ignore[reportMissingImports]
    ANALYTICAL_HORIZONS,
    CONSTANT_DEFAULT_RATE,
    CONSTANT_N_PERIODS,
    CONSTANT_START_DATE,
    VASICEK_N_PERIODS_LONG,
    VASICEK_N_PERIODS_SHORT,
    VASICEK_SEED,
    VASICEK_START_DATE,
    load_baseline,
)


if TYPE_CHECKING:
    from src.models.interest_rate.model_interest_rate_constant import (
        Interest_Rate_Model_Constant,
    )
    from src.models.interest_rate.model_interest_rate_standard import (
        Interest_Rate_Model_Standard,
    )


# ---------------------------------------------------------------------------
# Tolerances
# ---------------------------------------------------------------------------
_TOL_DETERMINISTIC: float = 1e-10  # constant model: exact match
_TOL_NUMERICAL: float = 1e-8  # floating-point rounding
_TOL_STOCHASTIC: float = 1e-6  # seeded Monte Carlo (platform variance)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _assert_dataframe_matches_baseline(
    actual: pl.DataFrame,
    baseline: pl.DataFrame,
    *,
    tolerance: float = _TOL_DETERMINISTIC,
    skip_date_col: bool = True,
) -> None:
    """Assert that *actual* matches *baseline* element-wise within *tolerance*.

    Parameters
    ----------
    actual : pl.DataFrame
        Freshly computed DataFrame.
    baseline : pl.DataFrame
        Baseline loaded from Parquet.
    tolerance : float
        Absolute tolerance for numeric columns.
    skip_date_col : bool
        If ``True``, skip comparison of the ``Date`` column (date ranges
        may differ in dtype but represent the same dates).
    """
    assert actual.shape == baseline.shape, (
        f"Shape mismatch: actual {actual.shape} vs baseline {baseline.shape}"
    )
    assert actual.columns == baseline.columns, (
        f"Column mismatch: actual {actual.columns} vs baseline {baseline.columns}"
    )

    for col_name in actual.columns:
        if skip_date_col and col_name == "Date":
            continue
        actual_vals = actual[col_name].to_numpy()
        baseline_vals = baseline[col_name].to_numpy()
        np.testing.assert_allclose(
            actual_vals,
            baseline_vals,
            atol=tolerance,
            rtol=0,
            err_msg=f"Column '{col_name}' differs from baseline",
        )


# =========================================================================
# CONSTANT MODEL — Default (hard-coded rate, empty-fit)
# =========================================================================


@pytest.mark.regression()
class Class_Test_Regression_Constant_Default:
    """Regression tests for Interest_Rate_Model_Constant with default rate."""

    def Test_Predict_Matches_Baseline(
        self,
        fitted_constant_default: Interest_Rate_Model_Constant,
    ) -> None:
        """Prediction output must match the stored baseline exactly."""
        actual = fitted_constant_default.predict(
            n_periods=CONSTANT_N_PERIODS,
            start_date=CONSTANT_START_DATE,
        )
        baseline = load_baseline("constant_predict_default")
        _assert_dataframe_matches_baseline(actual, baseline)

    def Test_Summary_Matches_Baseline(
        self,
        fitted_constant_default: Interest_Rate_Model_Constant,
    ) -> None:
        """Summary statistics must match the stored baseline."""
        pred = fitted_constant_default.predict(
            n_periods=CONSTANT_N_PERIODS,
            start_date=CONSTANT_START_DATE,
        )
        actual = fitted_constant_default.get_summary_statistics(pred)
        baseline = load_baseline("constant_summary_default")
        _assert_dataframe_matches_baseline(actual, baseline)

    def Test_Parameters_Match_Baseline(
        self,
        fitted_constant_default: Interest_Rate_Model_Constant,
    ) -> None:
        """Model parameters must match the stored baseline."""
        params = fitted_constant_default.parameters
        baseline = load_baseline("constant_parameters_default")
        for col_name in baseline.columns:
            assert params[col_name] == pytest.approx(
                baseline[col_name][0],
                abs=_TOL_DETERMINISTIC,
            )

    def Test_Annual_Rate_Equals_Default(
        self,
        fitted_constant_default: Interest_Rate_Model_Constant,
    ) -> None:
        """get_annual_rate must return the constructor-supplied rate."""
        assert fitted_constant_default.get_annual_rate() == pytest.approx(
            CONSTANT_DEFAULT_RATE,
            abs=_TOL_DETERMINISTIC,
        )

    def Test_All_Rates_Are_Constant(
        self,
        fitted_constant_default: Interest_Rate_Model_Constant,
    ) -> None:
        """Every row of prediction must have the same rate."""
        pred = fitted_constant_default.predict(
            n_periods=CONSTANT_N_PERIODS,
            start_date=CONSTANT_START_DATE,
        )
        rates = pred["short_rate"].to_numpy()
        np.testing.assert_allclose(
            rates,
            CONSTANT_DEFAULT_RATE,
            atol=_TOL_DETERMINISTIC,
        )

    def Test_Predict_Shape(
        self,
        fitted_constant_default: Interest_Rate_Model_Constant,
    ) -> None:
        """Prediction must have exactly n_periods rows."""
        pred = fitted_constant_default.predict(
            n_periods=CONSTANT_N_PERIODS,
            start_date=CONSTANT_START_DATE,
        )
        assert len(pred) == CONSTANT_N_PERIODS
        assert "Date" in pred.columns
        assert "short_rate" in pred.columns

    def Test_Daily_Frequency_Matches_Baseline(
        self,
        fitted_constant_default: Interest_Rate_Model_Constant,
    ) -> None:
        """Daily-frequency prediction must match baseline."""
        actual = fitted_constant_default.predict(
            n_periods=30,
            start_date=CONSTANT_START_DATE,
            freq="1d",
        )
        baseline = load_baseline("constant_predict_daily")
        _assert_dataframe_matches_baseline(actual, baseline)

    def Test_Yearly_Frequency_Matches_Baseline(
        self,
        fitted_constant_default: Interest_Rate_Model_Constant,
    ) -> None:
        """Yearly-frequency prediction must match baseline."""
        actual = fitted_constant_default.predict(
            n_periods=5,
            start_date=CONSTANT_START_DATE,
            freq="1y",
        )
        baseline = load_baseline("constant_predict_yearly")
        _assert_dataframe_matches_baseline(actual, baseline)


# =========================================================================
# CONSTANT MODEL — Fitted to historical data
# =========================================================================


@pytest.mark.regression()
class Class_Test_Regression_Constant_Fitted:
    """Regression tests for Interest_Rate_Model_Constant fitted to history."""

    def Test_Predict_Matches_Baseline(
        self,
        fitted_constant_historical: Interest_Rate_Model_Constant,
    ) -> None:
        """Prediction from fitted model must match stored baseline."""
        actual = fitted_constant_historical.predict(
            n_periods=CONSTANT_N_PERIODS,
            start_date=CONSTANT_START_DATE,
        )
        baseline = load_baseline("constant_predict_fitted")
        _assert_dataframe_matches_baseline(actual, baseline)

    def Test_Summary_Matches_Baseline(
        self,
        fitted_constant_historical: Interest_Rate_Model_Constant,
    ) -> None:
        """Summary statistics from fitted model must match baseline."""
        pred = fitted_constant_historical.predict(
            n_periods=CONSTANT_N_PERIODS,
            start_date=CONSTANT_START_DATE,
        )
        actual = fitted_constant_historical.get_summary_statistics(pred)
        baseline = load_baseline("constant_summary_fitted")
        _assert_dataframe_matches_baseline(actual, baseline)

    def Test_Parameters_Match_Baseline(
        self,
        fitted_constant_historical: Interest_Rate_Model_Constant,
    ) -> None:
        """Fitted parameters must match stored baseline."""
        params = fitted_constant_historical.parameters
        baseline = load_baseline("constant_parameters_fitted")
        for col_name in baseline.columns:
            assert params[col_name] == pytest.approx(
                baseline[col_name][0],
                abs=_TOL_NUMERICAL,
            )

    def Test_Fitted_Rate_Is_Mean_Of_Historical(
        self,
        fitted_constant_historical: Interest_Rate_Model_Constant,
        constant_historical_rates: pl.DataFrame,
    ) -> None:
        """Fitted rate must equal arithmetic mean of historical rates."""
        expected_mean = float(np.mean(constant_historical_rates["short_rate"].to_numpy()))
        assert fitted_constant_historical.get_annual_rate() == pytest.approx(
            expected_mean,
            abs=_TOL_NUMERICAL,
        )

    def Test_All_Rates_Are_Constant(
        self,
        fitted_constant_historical: Interest_Rate_Model_Constant,
    ) -> None:
        """Fitted model must still produce constant rates."""
        pred = fitted_constant_historical.predict(
            n_periods=CONSTANT_N_PERIODS,
            start_date=CONSTANT_START_DATE,
        )
        rates = pred["short_rate"].to_numpy()
        expected_rate = fitted_constant_historical.get_annual_rate()
        np.testing.assert_allclose(rates, expected_rate, atol=_TOL_DETERMINISTIC)

    def Test_Model_Is_Fitted(
        self,
        fitted_constant_historical: Interest_Rate_Model_Constant,
    ) -> None:
        """Model status must be FITTED after calling fit()."""
        assert fitted_constant_historical.is_fitted


# =========================================================================
# CONSTANT MODEL — Historical input data regression
# =========================================================================


@pytest.mark.regression()
class Class_Test_Regression_Constant_Historical_Data:
    """Verify that the canonical historical data matches baseline."""

    def Test_Historical_Rates_Match_Baseline(
        self,
        constant_historical_rates: pl.DataFrame,
    ) -> None:
        """Canonical historical data must match stored Parquet baseline."""
        baseline = load_baseline("constant_historical_rates")
        assert constant_historical_rates.shape == baseline.shape
        np.testing.assert_allclose(
            constant_historical_rates["short_rate"].to_numpy(),
            baseline["short_rate"].to_numpy(),
            atol=_TOL_DETERMINISTIC,
        )

    def Test_Historical_Rates_Shape(
        self,
        constant_historical_rates: pl.DataFrame,
    ) -> None:
        """Historical data must have 5 rows and correct columns."""
        assert len(constant_historical_rates) == 5
        assert "Date" in constant_historical_rates.columns
        assert "short_rate" in constant_historical_rates.columns


# =========================================================================
# VASICEK MODEL — Fitted parameters
# =========================================================================


@pytest.mark.regression()
class Class_Test_Regression_Vasicek_Fitted_Parameters:
    """Regression tests for Vasicek OLS-fitted parameters."""

    def Test_Parameters_Match_Baseline(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """All fitted parameters must match the stored baseline."""
        params = fitted_vasicek.parameters
        baseline = load_baseline("vasicek_parameters_fitted")
        for col_name in baseline.columns:
            assert params[col_name] == pytest.approx(
                baseline[col_name][0],
                abs=_TOL_NUMERICAL,
            ), f"Parameter '{col_name}' differs"

    def Test_Kappa_Is_Positive(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """Mean-reversion speed kappa must be positive."""
        assert fitted_vasicek.m_kappa > 0

    def Test_Sigma_Is_Positive(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """Volatility sigma must be positive."""
        assert fitted_vasicek.m_sigma > 0

    def Test_Theta_Is_Finite(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """Long-run mean theta must be finite."""
        assert np.isfinite(fitted_vasicek.m_theta)

    def Test_Model_Is_Fitted(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """Model status must be FITTED."""
        assert fitted_vasicek.is_fitted

    def Test_Annual_Rate_Equals_Theta(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """get_annual_rate must return theta for the Vasicek model."""
        assert fitted_vasicek.get_annual_rate() == pytest.approx(
            fitted_vasicek.m_theta,
            abs=_TOL_DETERMINISTIC,
        )


# =========================================================================
# VASICEK MODEL — Seeded predictions
# =========================================================================


@pytest.mark.regression()
class Class_Test_Regression_Vasicek_Predictions:
    """Regression tests for Vasicek seeded Monte Carlo predictions."""

    def Test_12_Month_Prediction_Matches_Baseline(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """12-month seeded prediction must match stored baseline."""
        actual = fitted_vasicek.predict(
            n_periods=VASICEK_N_PERIODS_SHORT,
            start_date=VASICEK_START_DATE,
            seed=VASICEK_SEED,
        )
        baseline = load_baseline("vasicek_predict_12mo")
        _assert_dataframe_matches_baseline(actual, baseline, tolerance=_TOL_STOCHASTIC)

    def Test_60_Month_Prediction_Matches_Baseline(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """60-month seeded prediction must match stored baseline."""
        actual = fitted_vasicek.predict(
            n_periods=VASICEK_N_PERIODS_LONG,
            start_date=VASICEK_START_DATE,
            seed=VASICEK_SEED,
        )
        baseline = load_baseline("vasicek_predict_60mo")
        _assert_dataframe_matches_baseline(actual, baseline, tolerance=_TOL_STOCHASTIC)

    def Test_12_Month_Prediction_Shape(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """12-month prediction must have correct shape and columns."""
        pred = fitted_vasicek.predict(
            n_periods=VASICEK_N_PERIODS_SHORT,
            start_date=VASICEK_START_DATE,
            seed=VASICEK_SEED,
        )
        assert len(pred) == VASICEK_N_PERIODS_SHORT
        expected_cols = {"Date", "Mean", "Median", "Std", "P5", "P25", "P75", "P95", "Min", "Max"}
        assert set(pred.columns) == expected_cols

    def Test_60_Month_Prediction_Shape(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """60-month prediction must have correct shape."""
        pred = fitted_vasicek.predict(
            n_periods=VASICEK_N_PERIODS_LONG,
            start_date=VASICEK_START_DATE,
            seed=VASICEK_SEED,
        )
        assert len(pred) == VASICEK_N_PERIODS_LONG

    def Test_Mean_Is_Between_P5_And_P95(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """Mean must lie within the 5th-95th percentile band."""
        pred = fitted_vasicek.predict(
            n_periods=VASICEK_N_PERIODS_SHORT,
            start_date=VASICEK_START_DATE,
            seed=VASICEK_SEED,
        )
        means = pred["Mean"].to_numpy()
        p5_vals = pred["P5"].to_numpy()
        p95_vals = pred["P95"].to_numpy()
        assert np.all(means >= p5_vals)
        assert np.all(means <= p95_vals)

    def Test_Std_Is_Non_Negative(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """Standard deviation must be non-negative for all periods."""
        pred = fitted_vasicek.predict(
            n_periods=VASICEK_N_PERIODS_SHORT,
            start_date=VASICEK_START_DATE,
            seed=VASICEK_SEED,
        )
        assert np.all(pred["Std"].to_numpy() >= 0)

    def Test_Min_Leq_Mean_Leq_Max(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """Min <= Mean <= Max for every period."""
        pred = fitted_vasicek.predict(
            n_periods=VASICEK_N_PERIODS_SHORT,
            start_date=VASICEK_START_DATE,
            seed=VASICEK_SEED,
        )
        assert np.all(pred["Min"].to_numpy() <= pred["Mean"].to_numpy())
        assert np.all(pred["Mean"].to_numpy() <= pred["Max"].to_numpy())

    def Test_Daily_Prediction_Matches_Baseline(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """Daily-frequency seeded prediction must match baseline."""
        actual = fitted_vasicek.predict(
            n_periods=30,
            start_date=VASICEK_START_DATE,
            freq="1d",
            seed=VASICEK_SEED,
        )
        baseline = load_baseline("vasicek_predict_daily")
        _assert_dataframe_matches_baseline(actual, baseline, tolerance=_TOL_STOCHASTIC)

    def Test_Reproducibility_With_Same_Seed(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """Two calls with the same seed must produce identical results."""
        pred_a = fitted_vasicek.predict(
            n_periods=VASICEK_N_PERIODS_SHORT,
            start_date=VASICEK_START_DATE,
            seed=VASICEK_SEED,
        )
        pred_b = fitted_vasicek.predict(
            n_periods=VASICEK_N_PERIODS_SHORT,
            start_date=VASICEK_START_DATE,
            seed=VASICEK_SEED,
        )
        _assert_dataframe_matches_baseline(pred_a, pred_b, tolerance=_TOL_DETERMINISTIC)


# =========================================================================
# VASICEK MODEL — Summary statistics
# =========================================================================


@pytest.mark.regression()
class Class_Test_Regression_Vasicek_Summary:
    """Regression tests for Vasicek summary statistics."""

    def Test_Summary_12_Month_Matches_Baseline(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """Summary statistics of the 12-month mean path must match baseline."""
        pred = fitted_vasicek.predict(
            n_periods=VASICEK_N_PERIODS_SHORT,
            start_date=VASICEK_START_DATE,
            seed=VASICEK_SEED,
        )
        summary_input = pl.DataFrame({"short_rate": pred["Mean"]})
        actual = fitted_vasicek.get_summary_statistics(summary_input)
        baseline = load_baseline("vasicek_summary_12mo")
        _assert_dataframe_matches_baseline(actual, baseline, tolerance=_TOL_STOCHASTIC)


# =========================================================================
# VASICEK MODEL — Analytical formulas
# =========================================================================


@pytest.mark.regression()
class Class_Test_Regression_Vasicek_Analytical:
    """Regression tests for Vasicek analytical mean and variance formulas."""

    def Test_Analytical_Mean_Matches_Baseline(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """Analytical conditional mean must match stored baseline."""
        baseline = load_baseline("vasicek_analytical_mean")
        for idx_row in range(len(baseline)):
            t_val = float(baseline["t_years"][idx_row])
            expected = float(baseline["analytical_mean"][idx_row])
            actual = fitted_vasicek.get_analytical_mean(t_years=t_val)
            assert actual == pytest.approx(expected, abs=_TOL_NUMERICAL), (
                f"Analytical mean at t={t_val} differs: {actual} vs {expected}"
            )

    def Test_Analytical_Variance_Matches_Baseline(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """Analytical conditional variance must match stored baseline."""
        baseline = load_baseline("vasicek_analytical_variance")
        for idx_row in range(len(baseline)):
            t_val = float(baseline["t_years"][idx_row])
            expected = float(baseline["analytical_variance"][idx_row])
            actual = fitted_vasicek.get_analytical_variance(t_years=t_val)
            assert actual == pytest.approx(expected, abs=_TOL_NUMERICAL), (
                f"Analytical variance at t={t_val} differs: {actual} vs {expected}"
            )

    def Test_Variance_Increases_With_Horizon(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """Conditional variance must be non-decreasing in time."""
        variances = [
            fitted_vasicek.get_analytical_variance(t_years=t_val) for t_val in ANALYTICAL_HORIZONS
        ]
        for idx_pair in range(len(variances) - 1):
            assert variances[idx_pair] <= variances[idx_pair + 1] + _TOL_NUMERICAL

    def Test_Variance_Is_Non_Negative(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """Conditional variance must be non-negative for all horizons."""
        for t_val in ANALYTICAL_HORIZONS:
            assert fitted_vasicek.get_analytical_variance(t_years=t_val) >= 0

    def Test_Mean_Converges_To_Theta(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """At long horizon the conditional mean approaches theta."""
        long_horizon_mean = fitted_vasicek.get_analytical_mean(t_years=100.0)
        assert long_horizon_mean == pytest.approx(
            fitted_vasicek.m_theta,
            abs=1e-6,
        )

    def Test_Stationary_Variance_Limit(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        r"""At long horizon, variance approaches sigma^2 / (2*kappa)."""
        long_var = fitted_vasicek.get_analytical_variance(t_years=100.0)
        stationary_var = fitted_vasicek.m_sigma**2 / (2.0 * fitted_vasicek.m_kappa)
        assert long_var == pytest.approx(stationary_var, abs=1e-6)


# =========================================================================
# VASICEK MODEL — Historical input data regression
# =========================================================================


@pytest.mark.regression()
class Class_Test_Regression_Vasicek_Historical_Data:
    """Verify that the canonical Vasicek historical data matches baseline."""

    def Test_Historical_Rates_Match_Baseline(
        self,
        vasicek_historical_rates: pl.DataFrame,
    ) -> None:
        """Canonical historical rates must match stored baseline."""
        baseline = load_baseline("vasicek_historical_rates")
        assert vasicek_historical_rates.shape == baseline.shape
        np.testing.assert_allclose(
            vasicek_historical_rates["short_rate"].to_numpy(),
            baseline["short_rate"].to_numpy(),
            atol=_TOL_DETERMINISTIC,
        )

    def Test_Historical_Rates_Shape(
        self,
        vasicek_historical_rates: pl.DataFrame,
    ) -> None:
        """Historical data must have 120 rows and correct columns."""
        assert len(vasicek_historical_rates) == 120
        assert "Date" in vasicek_historical_rates.columns
        assert "short_rate" in vasicek_historical_rates.columns

    def Test_Historical_Rates_Are_Finite(
        self,
        vasicek_historical_rates: pl.DataFrame,
    ) -> None:
        """All historical rates must be finite."""
        rates = vasicek_historical_rates["short_rate"].to_numpy()
        assert np.all(np.isfinite(rates))


# =========================================================================
# CROSS-MODEL CONSISTENCY
# =========================================================================


@pytest.mark.regression()
class Class_Test_Regression_Cross_Model_Consistency:
    """Consistency checks across constant and Vasicek models."""

    def Test_Both_Models_Are_Fitted(
        self,
        fitted_constant_default: Interest_Rate_Model_Constant,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """Both models must report FITTED status."""
        assert fitted_constant_default.is_fitted
        assert fitted_vasicek.is_fitted

    def Test_Predict_Same_Columns_Date_Short_Rate_For_Constant(
        self,
        fitted_constant_default: Interest_Rate_Model_Constant,
    ) -> None:
        """Constant model predict output must have Date and short_rate."""
        pred = fitted_constant_default.predict(n_periods=3, start_date="2025-01-01")
        assert set(pred.columns) == {"Date", "short_rate"}

    def Test_Vasicek_Predict_Has_Statistical_Columns(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """Vasicek predict output must have Date and all stat columns."""
        pred = fitted_vasicek.predict(n_periods=3, start_date="2025-01-01", seed=42)
        expected_cols = {"Date", "Mean", "Median", "Std", "P5", "P25", "P75", "P95", "Min", "Max"}
        assert set(pred.columns) == expected_cols

    def Test_Vasicek_Mean_Stays_Reasonable(
        self,
        fitted_vasicek: Interest_Rate_Model_Standard,
    ) -> None:
        """Vasicek mean path should stay within [-0.10, 0.50] over 60 months."""
        pred = fitted_vasicek.predict(
            n_periods=VASICEK_N_PERIODS_LONG,
            start_date=VASICEK_START_DATE,
            seed=VASICEK_SEED,
        )
        means = pred["Mean"].to_numpy()
        assert np.all(means > -0.10)
        assert np.all(means < 0.50)
