"""Regression tests for Inflation_Model_Standard (OU / Vasicek process).

These tests verify that the stochastic inflation model outputs do not change
unexpectedly across code changes, package upgrades, or refactors.

Test Strategy
-------------
Each test:
1. Loads a pre-computed baseline Parquet file (generated by ``generate_baselines.py``).
2. Runs the same model operations with identical fixed-seed input data.
3. Compares every value against the baseline within the stated tolerance.

Tolerances
----------
* **Fitted parameters** (OLS on differences): ``abs=1e-10`` — deterministic if the
  same input data is used.
* **Monte Carlo predictions** (seeded): ``abs=1e-8`` — the RNG seed is pinned (99),
  giving fully reproducible paths on the same platform.
* **Analytical formulas**: ``abs=1e-12`` — closed-form, no stochastic component.

Baseline Regeneration
---------------------
If a test fails because of an *intentional* algorithmic change::

    python tests/regression_data/inflation/generate_baselines.py

Then commit both the code changes and the updated Parquet files together.
"""

from __future__ import annotations

import logging

import polars as pl
import pytest

from src.models.inflation.model_inflation_standard import Inflation_Model_Standard  # noqa: TC001

from tests.tests_regression.models.inflation.conftest import (
    PREDICT_SEED,
    load_baseline,
)


logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Tolerances
# ---------------------------------------------------------------------------
_TOL_PARAMETERS: float = 1e-10
_TOL_MONTE_CARLO: float = 1e-8
_TOL_ANALYTICAL: float = 1e-12


# =============================================================================
# Helper
# =============================================================================


def _assert_dataframe_matches_baseline(
    current: pl.DataFrame,
    baseline: pl.DataFrame,
    *,
    tolerance: float,
    label: str = "",
) -> None:
    """Compare two Polars DataFrames element-by-element within tolerance.

    Parameters
    ----------
    current:
        DataFrame produced by re-running the model in this test session.
    baseline:
        DataFrame loaded from the Parquet baseline file.
    tolerance:
        Absolute tolerance for numeric comparisons.
    label:
        Optional label used in error messages.

    Raises
    ------
    AssertionError
        If shapes differ or any numeric value deviates beyond ``tolerance``.
    """
    assert current.shape == baseline.shape, (
        f"Shape mismatch {label}: current={current.shape}, baseline={baseline.shape}"
    )

    assert current.columns == baseline.columns, (
        f"Column mismatch {label}: current={current.columns}, baseline={baseline.columns}"
    )

    mismatches: list[str] = []
    for col in current.columns:
        if current[col].dtype in (pl.Float32, pl.Float64):
            for i in range(len(current)):
                c_val = float(current[col][i])
                b_val = float(baseline[col][i])
                diff = abs(c_val - b_val)
                if diff > tolerance:
                    mismatches.append(
                        f"  [{i}] {col}: baseline={b_val:.12e}  "
                        f"current={c_val:.12e}  diff={diff:.2e}",
                    )

    assert not mismatches, f"Regression failure {label} (tolerance={tolerance:.2e}):\n" + "\n".join(
        mismatches
    )


# =============================================================================
# Regression tests — Standard model fitted on annual data
# =============================================================================


@pytest.mark.regression()
class Class_Test_Regression_Standard_Annual:
    """Regression: standard OU model fitted on canonical 10-year annual data."""

    def Test_Parameters_Match_Baseline(
        self,
        fitted_standard_annual: Inflation_Model_Standard,
    ) -> None:
        """Fitted parameters (kappa, theta, sigma) must match baseline."""
        params = fitted_standard_annual.parameters
        params_df = pl.DataFrame({key: [value] for key, value in params.items()})
        baseline_df = load_baseline("standard_fitted_annual_parameters")

        _assert_dataframe_matches_baseline(
            params_df,
            baseline_df,
            tolerance=_TOL_PARAMETERS,
            label="standard_fitted_annual_parameters",
        )

    def Test_Predict_12_Months_Matches_Baseline(
        self,
        fitted_standard_annual: Inflation_Model_Standard,
    ) -> None:
        """12-month seeded prediction must match stored baseline."""
        df_current = fitted_standard_annual.predict(
            n_periods=12,
            start_date="2025-01-01",
            freq="1mo",
            seed=PREDICT_SEED,
        )
        df_baseline = load_baseline("standard_fitted_annual_predict_12mo")

        _assert_dataframe_matches_baseline(
            df_current,
            df_baseline,
            tolerance=_TOL_MONTE_CARLO,
            label="standard_fitted_annual_predict_12mo",
        )

    def Test_Predict_Row_Count_Is_12(
        self,
        fitted_standard_annual: Inflation_Model_Standard,
    ) -> None:
        """Prediction must contain exactly 12 rows."""
        df_current = fitted_standard_annual.predict(
            n_periods=12,
            start_date="2025-01-01",
            freq="1mo",
            seed=PREDICT_SEED,
        )
        assert len(df_current) == 12

    def Test_Predict_Columns_Are_Correct(
        self,
        fitted_standard_annual: Inflation_Model_Standard,
    ) -> None:
        """Prediction must have the expected statistical summary columns."""
        df_current = fitted_standard_annual.predict(
            n_periods=12,
            start_date="2025-01-01",
            freq="1mo",
            seed=PREDICT_SEED,
        )
        expected_cols = {"Date", "Mean", "Median", "Std", "P5", "P25", "P75", "P95", "Min", "Max"}
        assert set(df_current.columns) == expected_cols

    def Test_Summary_Statistics_Match_Baseline(
        self,
        fitted_standard_annual: Inflation_Model_Standard,
    ) -> None:
        """Aggregate summary of prediction must match baseline."""
        df_predict = fitted_standard_annual.predict(
            n_periods=12,
            start_date="2025-01-01",
            freq="1mo",
            seed=PREDICT_SEED,
        )
        summary_df = pl.DataFrame(
            {
                "Mean_Rate": [df_predict["Mean"].mean()],
                "Median_Rate": [df_predict["Median"].mean()],
                "Mean_Std": [df_predict["Std"].mean()],
                "Mean_P5": [df_predict["P5"].mean()],
                "Mean_P95": [df_predict["P95"].mean()],
            },
        )
        baseline_df = load_baseline("standard_fitted_annual_summary")

        _assert_dataframe_matches_baseline(
            summary_df,
            baseline_df,
            tolerance=_TOL_MONTE_CARLO,
            label="standard_fitted_annual_summary",
        )

    def Test_Get_Annual_Rate_Returns_Theta(
        self,
        fitted_standard_annual: Inflation_Model_Standard,
    ) -> None:
        """get_annual_rate() must return theta (long-run mean)."""
        rate = fitted_standard_annual.get_annual_rate()
        params = fitted_standard_annual.parameters
        assert rate == pytest.approx(params["theta"], abs=_TOL_PARAMETERS)

    def Test_Seeded_Predict_Is_Reproducible(
        self,
        fitted_standard_annual: Inflation_Model_Standard,
    ) -> None:
        """Two consecutive seeded predictions must yield identical results."""
        df_a = fitted_standard_annual.predict(
            n_periods=12,
            start_date="2025-01-01",
            freq="1mo",
            seed=PREDICT_SEED,
        )
        df_b = fitted_standard_annual.predict(
            n_periods=12,
            start_date="2025-01-01",
            freq="1mo",
            seed=PREDICT_SEED,
        )
        _assert_dataframe_matches_baseline(
            df_a,
            df_b,
            tolerance=1e-15,
            label="reproducibility_check",
        )


# =============================================================================
# Regression tests — Standard model fitted on monthly data
# =============================================================================


@pytest.mark.regression()
class Class_Test_Regression_Standard_Monthly:
    """Regression: standard OU model fitted on canonical 48-month data."""

    def Test_Predict_24_Months_Matches_Baseline(
        self,
        fitted_standard_monthly: Inflation_Model_Standard,
    ) -> None:
        """24-month seeded prediction must match stored baseline."""
        df_current = fitted_standard_monthly.predict(
            n_periods=24,
            start_date="2025-01-01",
            freq="1mo",
            seed=PREDICT_SEED,
        )
        df_baseline = load_baseline("standard_fitted_monthly_predict_24mo")

        _assert_dataframe_matches_baseline(
            df_current,
            df_baseline,
            tolerance=_TOL_MONTE_CARLO,
            label="standard_fitted_monthly_predict_24mo",
        )

    def Test_Predict_Row_Count_Is_24(
        self,
        fitted_standard_monthly: Inflation_Model_Standard,
    ) -> None:
        """Monthly prediction must contain exactly 24 rows."""
        df_current = fitted_standard_monthly.predict(
            n_periods=24,
            start_date="2025-01-01",
            freq="1mo",
            seed=PREDICT_SEED,
        )
        assert len(df_current) == 24

    def Test_Monthly_Fitted_Parameters_Are_Stored(
        self,
        fitted_standard_monthly: Inflation_Model_Standard,
    ) -> None:
        """Fitted model must expose kappa, theta, sigma, current_rate."""
        params = fitted_standard_monthly.parameters
        expected_keys = {"kappa", "theta", "sigma", "current_rate", "dt_years"}
        assert set(params.keys()) == expected_keys

    def Test_Monthly_Mean_Converges_To_Theta(
        self,
        fitted_standard_monthly: Inflation_Model_Standard,
    ) -> None:
        """Long-horizon mean prediction should converge towards theta."""
        df_long = fitted_standard_monthly.predict(
            n_periods=120,
            start_date="2025-01-01",
            freq="1mo",
            seed=PREDICT_SEED,
        )
        theta = fitted_standard_monthly.parameters["theta"]
        last_mean = float(df_long["Mean"][-1])
        # With 120 months (10 years) of OU, the mean should be near theta
        assert last_mean == pytest.approx(theta, abs=0.005)


# =============================================================================
# Regression tests — Analytical mean and variance
# =============================================================================


@pytest.mark.regression()
class Class_Test_Regression_Standard_Analytical:
    """Regression: closed-form analytical mean and variance formulas."""

    def Test_Analytical_Mean_Variance_Match_Baseline(
        self,
        fitted_standard_annual: Inflation_Model_Standard,
    ) -> None:
        """Analytical mean and variance at multiple horizons must match baseline."""
        horizons = [0.5, 1.0, 2.0, 5.0, 10.0]
        rows = []
        for t_yr in horizons:
            mean_val = fitted_standard_annual.get_analytical_mean(t_yr)
            var_val = fitted_standard_annual.get_analytical_variance(t_yr)
            rows.append(
                {
                    "T_Years": t_yr,
                    "Analytical_Mean": mean_val,
                    "Analytical_Variance": var_val,
                },
            )
        df_current = pl.DataFrame(rows)
        df_baseline = load_baseline("standard_analytical_mean_variance")

        _assert_dataframe_matches_baseline(
            df_current,
            df_baseline,
            tolerance=_TOL_ANALYTICAL,
            label="standard_analytical_mean_variance",
        )

    def Test_Analytical_Variance_Monotonically_Increasing(
        self,
        fitted_standard_annual: Inflation_Model_Standard,
    ) -> None:
        """Variance must increase with time horizon (OU mean-reverting)."""
        horizons = [0.5, 1.0, 2.0, 5.0, 10.0, 20.0]
        variances = [fitted_standard_annual.get_analytical_variance(t) for t in horizons]
        for i in range(1, len(variances)):
            assert variances[i] >= variances[i - 1], (
                f"Variance decreased from t={horizons[i - 1]} to t={horizons[i]}: "
                f"{variances[i - 1]:.8e} > {variances[i]:.8e}"
            )

    def Test_Analytical_Variance_Near_Zero_Is_Near_Zero(
        self,
        fitted_standard_annual: Inflation_Model_Standard,
    ) -> None:
        """Variance at very small t must be near zero."""
        var_small = fitted_standard_annual.get_analytical_variance(1e-6)
        assert var_small == pytest.approx(0.0, abs=1e-6)

    def Test_Analytical_Mean_Near_Zero_Equals_Current_Rate(
        self,
        fitted_standard_annual: Inflation_Model_Standard,
    ) -> None:
        """Mean at very small t must be approximately the current rate."""
        mean_small = fitted_standard_annual.get_analytical_mean(1e-6)
        current_rate = fitted_standard_annual.parameters["current_rate"]
        assert mean_small == pytest.approx(current_rate, abs=1e-6)

    def Test_Analytical_Mean_At_Large_T_Equals_Theta(
        self,
        fitted_standard_annual: Inflation_Model_Standard,
    ) -> None:
        """Mean at very large t must converge to theta (long-run mean)."""
        mean_100 = fitted_standard_annual.get_analytical_mean(100.0)
        theta = fitted_standard_annual.parameters["theta"]
        assert mean_100 == pytest.approx(theta, abs=1e-6)

    def Test_Analytical_Variance_Converges_To_Stationary(
        self,
        fitted_standard_annual: Inflation_Model_Standard,
    ) -> None:
        r"""Variance at large t must converge to stationary value :math:`\sigma^2/(2\kappa)`.

        The OU process has stationary variance $\frac{\sigma^2}{2\kappa}$.
        """
        params = fitted_standard_annual.parameters
        kappa = params["kappa"]
        sigma = params["sigma"]
        stationary_var = sigma**2 / (2.0 * kappa)
        var_100 = fitted_standard_annual.get_analytical_variance(100.0)
        assert var_100 == pytest.approx(stationary_var, abs=1e-6)
