"""Regression tests for Inflation_Model_Constant.

These tests verify that constant inflation model outputs do not change
unexpectedly across code changes, package upgrades, or refactors.

Test Strategy
-------------
Each test:
1. Loads a pre-computed baseline Parquet file (generated by ``generate_baselines.py``).
2. Runs the same model operations with identical fixed-seed input data.
3. Compares every value against the baseline within the stated tolerance.

Tolerances
----------
* Constant model outputs are **deterministic**.  Tolerance is ``abs=1e-10``.

Baseline Regeneration
---------------------
If a test fails because of an *intentional* algorithmic change::

    python tests/regression_data/inflation/generate_baselines.py

Then commit both the code changes and the updated Parquet files together.
"""

from __future__ import annotations

import logging

import polars as pl
import pytest

from src.models.inflation.model_inflation_constant import Inflation_Model_Constant  # noqa: TC001

from tests.tests_regression.models.inflation.conftest import load_baseline


logger = logging.getLogger(__name__)

# Absolute tolerance for deterministic constant model
_TOL_DETERMINISTIC: float = 1e-10


# =============================================================================
# Helper
# =============================================================================


def _assert_dataframe_matches_baseline(
    current: pl.DataFrame,
    baseline: pl.DataFrame,
    *,
    tolerance: float = _TOL_DETERMINISTIC,
    label: str = "",
) -> None:
    """Compare two Polars DataFrames element-by-element within tolerance.

    Parameters
    ----------
    current:
        DataFrame produced by re-running the model in this test session.
    baseline:
        DataFrame loaded from the Parquet baseline file.
    tolerance:
        Absolute tolerance for numeric comparisons.
    label:
        Optional label used in error messages.

    Raises
    ------
    AssertionError
        If shapes differ or any numeric value deviates beyond ``tolerance``.
    """
    assert current.shape == baseline.shape, (
        f"Shape mismatch {label}: current={current.shape}, baseline={baseline.shape}"
    )

    assert current.columns == baseline.columns, (
        f"Column mismatch {label}: current={current.columns}, baseline={baseline.columns}"
    )

    mismatches: list[str] = []
    for col in current.columns:
        if current[col].dtype in (pl.Float32, pl.Float64):
            for i in range(len(current)):
                c_val = float(current[col][i])
                b_val = float(baseline[col][i])
                diff = abs(c_val - b_val)
                if diff > tolerance:
                    mismatches.append(
                        f"  [{i}] {col}: baseline={b_val:.12e}  "
                        f"current={c_val:.12e}  diff={diff:.2e}",
                    )

    assert not mismatches, f"Regression failure {label} (tolerance={tolerance:.2e}):\n" + "\n".join(
        mismatches
    )


# =============================================================================
# Regression tests — Constant model with default rate
# =============================================================================


@pytest.mark.regression()
class Class_Test_Regression_Constant_Default:
    """Regression: constant model with default 2.5 % rate."""

    def Test_Predict_12_Months_Matches_Baseline(
        self,
        fitted_constant_default: Inflation_Model_Constant,
    ) -> None:
        """Predict output with default rate must match stored baseline."""
        df_current = fitted_constant_default.predict(
            n_periods=12,
            start_date="2025-01-01",
            freq="1mo",
        )
        df_baseline = load_baseline("constant_default_predict_12mo")

        _assert_dataframe_matches_baseline(
            df_current,
            df_baseline,
            label="constant_default_predict_12mo",
        )

    def Test_Predict_Row_Count_Is_12(
        self,
        fitted_constant_default: Inflation_Model_Constant,
    ) -> None:
        """Default predict must return exactly 12 rows for 12 periods."""
        df_current = fitted_constant_default.predict(
            n_periods=12,
            start_date="2025-01-01",
            freq="1mo",
        )
        assert len(df_current) == 12

    def Test_All_Rates_Equal_Default_Rate(
        self,
        fitted_constant_default: Inflation_Model_Constant,
    ) -> None:
        """Every row in the prediction must carry the default rate 0.025."""
        df_current = fitted_constant_default.predict(
            n_periods=12,
            start_date="2025-01-01",
            freq="1mo",
        )
        expected_rate = 0.025
        for i in range(len(df_current)):
            assert float(df_current["inflation_rate"][i]) == pytest.approx(
                expected_rate,
                abs=_TOL_DETERMINISTIC,
            )

    def Test_Get_Annual_Rate_Matches_Default(
        self,
        fitted_constant_default: Inflation_Model_Constant,
    ) -> None:
        """get_annual_rate must return 0.025 for default-fitted model."""
        rate = fitted_constant_default.get_annual_rate()
        assert rate == pytest.approx(0.025, abs=_TOL_DETERMINISTIC)


# =============================================================================
# Regression tests — Constant model fitted on historical data
# =============================================================================


@pytest.mark.regression()
class Class_Test_Regression_Constant_Fitted_Historical:
    """Regression: constant model fitted on 5-year historical data."""

    def Test_Predict_12_Months_Matches_Baseline(
        self,
        fitted_constant_historical: Inflation_Model_Constant,
    ) -> None:
        """Predict output from historical-fitted model must match baseline."""
        df_current = fitted_constant_historical.predict(
            n_periods=12,
            start_date="2025-01-01",
            freq="1mo",
        )
        df_baseline = load_baseline("constant_fitted_historical_predict_12mo")

        _assert_dataframe_matches_baseline(
            df_current,
            df_baseline,
            label="constant_fitted_historical_predict_12mo",
        )

    def Test_Fitted_Rate_Is_Mean_Of_Historical(
        self,
        fitted_constant_historical: Inflation_Model_Constant,
    ) -> None:
        """Fitted rate must equal the arithmetic mean of input rates."""
        import numpy as np

        expected = float(np.mean([0.023, 0.047, 0.080, 0.034, 0.032]))
        actual = fitted_constant_historical.get_annual_rate()
        assert actual == pytest.approx(expected, abs=_TOL_DETERMINISTIC)

    def Test_Summary_Statistics_Match_Baseline(
        self,
        fitted_constant_historical: Inflation_Model_Constant,
    ) -> None:
        """Summary statistics on prediction must match baseline exactly."""
        df_predict = fitted_constant_historical.predict(
            n_periods=12,
            start_date="2025-01-01",
            freq="1mo",
        )
        df_summary_current = fitted_constant_historical.get_summary_statistics(
            df_predict,
        )
        df_summary_baseline = load_baseline("constant_fitted_historical_summary")

        _assert_dataframe_matches_baseline(
            df_summary_current,
            df_summary_baseline,
            label="constant_fitted_historical_summary",
        )

    def Test_Predict_Row_Count_Is_12(
        self,
        fitted_constant_historical: Inflation_Model_Constant,
    ) -> None:
        """Historical-fitted model predict must return 12 rows."""
        df_current = fitted_constant_historical.predict(
            n_periods=12,
            start_date="2025-01-01",
            freq="1mo",
        )
        assert len(df_current) == 12

    def Test_All_Rates_Are_Constant(
        self,
        fitted_constant_historical: Inflation_Model_Constant,
    ) -> None:
        """Every row must carry the same constant rate."""
        df_current = fitted_constant_historical.predict(
            n_periods=12,
            start_date="2025-01-01",
            freq="1mo",
        )
        rates = df_current["inflation_rate"].to_list()
        assert all(r == pytest.approx(rates[0], abs=_TOL_DETERMINISTIC) for r in rates)

    def Test_Parameters_Dict_Contains_Annual_Rate(
        self,
        fitted_constant_historical: Inflation_Model_Constant,
    ) -> None:
        """Parameters dict must contain 'annual_rate' key after fitting."""
        params = fitted_constant_historical.parameters
        assert "annual_rate" in params
        import numpy as np

        expected = float(np.mean([0.023, 0.047, 0.080, 0.034, 0.032]))
        assert params["annual_rate"] == pytest.approx(expected, abs=_TOL_DETERMINISTIC)
